import Foundation
import GRDB

// MARK: — SQL helpers

extension FirstName {
    var insertArguments: [DatabaseValueConvertible] {
        let themesJSON = (try? JSONEncoder().encode(themes)).flatMap { String(data: $0, encoding: .utf8) } ?? "[]"
        return [
            id, name, gender.rawValue, origin, originLocale as DatabaseValueConvertible? ?? DatabaseValue.null,
            meaning, syllables,
            popularityRankFR as DatabaseValueConvertible? ?? DatabaseValue.null,
            popularityRankUS as DatabaseValueConvertible? ?? DatabaseValue.null,
            themesJSON,
            phonetic as DatabaseValueConvertible? ?? DatabaseValue.null
        ]
    }
}

// MARK: — Hardcoded catalog

enum HardcodedNames {

    static let createTableSQL = """
        CREATE TABLE IF NOT EXISTS names (
            id                  INTEGER PRIMARY KEY,
            name                TEXT NOT NULL,
            gender              TEXT NOT NULL DEFAULT 'unisex',
            origin              TEXT NOT NULL DEFAULT '',
            origin_locale       TEXT,
            meaning             TEXT NOT NULL DEFAULT '',
            syllables           INTEGER NOT NULL DEFAULT 1,
            popularity_rank_fr  INTEGER,
            popularity_rank_us  INTEGER,
            themes              TEXT,
            phonetic            TEXT
        )
        """

    static let insertSQL = """
        INSERT OR REPLACE INTO names
            (id, name, gender, origin, origin_locale, meaning, syllables,
             popularity_rank_fr, popularity_rank_us, themes, phonetic)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """

    // swiftlint:disable function_body_length
    static let all: [FirstName] = [
        // ── French top 50 girls ───────────────────────────────────────────────
        fn(1,  "Emma",      .female, "Germanique", "de-DE", "entière, universelle", 2, 1,  1,  ["nature"]),
        fn(2,  "Jade",      .female, "Espagnol",   "es-ES", "pierre précieuse verte", 1, 2, 56, ["nature", "mineral"]),
        fn(3,  "Louise",    .female, "Germanique", "de-DE", "guerrière célèbre", 2, 3, 324, ["classique"]),
        fn(4,  "Alice",     .female, "Germanique", "de-DE", "de noble nature", 2, 4,  9,  ["classique", "litterature"]),
        fn(5,  "Chloé",     .female, "Grec",       "el-GR", "pousse verte, floraison", 2, 5, 104, ["nature"]),
        fn(6,  "Inès",      .female, "Latin",      "la",    "pure, chaste", 2, 6, 228, ["classique"]),
        fn(7,  "Léa",       .female, "Hébreu",     "he-IL", "fatiguée ou lasse", 2, 7, 166, ["biblique"]),
        fn(8,  "Manon",     .female, "Hébreu",     "he-IL", "grâce divine", 2, 8,  nil, ["classique"]),
        fn(9,  "Camille",   .unisex, "Latin",      "la",    "enfant de cérémonie", 2, 9, 193, ["classique"]),
        fn(10, "Zoé",       .female, "Grec",       "el-GR", "la vie", 2, 10, 32, ["vitalite"]),
        fn(11, "Clara",     .female, "Latin",      "la",    "lumineuse, brillante", 2, 11, 130, ["lumiere"]),
        fn(12, "Lucie",     .female, "Latin",      "la",    "lumière", 2, 12, 270, ["lumiere"]),
        fn(13, "Ambre",     .female, "Arabe",      "ar-SA", "résine fossile dorée", 1, 13, nil, ["nature", "mineral"]),
        fn(14, "Lola",      .female, "Espagnol",   "es-ES", "douleurs de la Vierge", 2, 14, 107, ["classique"]),
        fn(15, "Eva",       .female, "Hébreu",     "he-IL", "vie, vivante", 2, 15, 74, ["biblique"]),
        fn(16, "Rose",      .female, "Latin",      "la",    "la rose", 1, 16,  138, ["nature", "fleur"]),
        fn(17, "Lily",      .female, "Anglais",    "en-GB", "le lys", 2, 17,  4,  ["nature", "fleur"]),
        fn(18, "Anaïs",     .female, "Hébreu",     "he-IL", "grâce divine", 2, 18, nil, ["classique"]),
        fn(19, "Sarah",     .female, "Hébreu",     "he-IL", "princesse", 2, 19, 57, ["biblique"]),
        fn(20, "Juliette",  .female, "Latin",      "la",    "jeune, de la gens Julia", 3, 20, 246, ["classique", "litterature"]),
        fn(21, "Elisa",     .female, "Hébreu",     "he-IL", "Dieu est ma promesse", 3, 21, 231, ["biblique"]),
        fn(22, "Léonie",    .female, "Latin",      "la",    "lionner, courageuse", 3, 22, nil, ["nature", "force"]),
        fn(23, "Nina",      .female, "Espagnol",   "es-ES", "petite fille", 2, 23, 347, ["douceur"]),
        fn(24, "Margot",    .female, "Grec",       "el-GR", "perle", 2, 24, nil, ["classique"]),
        fn(25, "Elisa",     .female, "Hébreu",     "he-IL", "Dieu est ma promesse", 3, 25, 231, ["biblique"]),
        fn(26, "Charlotte", .female, "Germanique", "de-DE", "femme libre", 3, 26, 6,  ["classique"]),
        fn(27, "Léa",       .female, "Hébreu",     "he-IL", "fatiguée", 2, 27, 166, ["biblique"]),
        fn(28, "Mathilde",  .female, "Germanique", "de-DE", "force au combat", 2, 28, nil, ["force"]),
        fn(29, "Pauline",   .female, "Latin",      "la",    "humble, petite", 2, 29, nil, ["classique"]),
        fn(30, "Océane",    .female, "Grec",       "el-GR", "de l'océan", 3, 30, nil, ["nature", "mer"]),
        fn(31, "Clémence",  .female, "Latin",      "la",    "clémence, douceur", 2, 31, nil, ["vertu"]),
        fn(32, "Noémie",    .female, "Hébreu",     "he-IL", "ma douceur, ma joie", 3, 32, nil, ["joie"]),
        fn(33, "Élise",     .female, "Hébreu",     "he-IL", "Dieu est ma promesse", 2, 33, nil, ["biblique"]),
        fn(34, "Inaya",     .female, "Arabe",      "ar-SA", "don du ciel, sollicitude", 3, 34, nil, ["spirituel"]),
        fn(35, "Céline",    .female, "Latin",      "la",    "céleste", 2, 35, nil, ["spirituel"]),
        fn(36, "Laura",     .female, "Latin",      "la",    "laurier, victoire", 2, 36, 22, ["nature", "victoire"]),
        fn(37, "Sophie",    .female, "Grec",       "el-GR", "sagesse", 2, 37, 81, ["sagesse"]),
        fn(38, "Yaël",      .female, "Hébreu",     "he-IL", "chèvre des montagnes", 2, 38, nil, ["biblique"]),
        fn(39, "Marie",     .female, "Hébreu",     "he-IL", "mer de l'amertume ou étoile de la mer", 2, 39, nil, ["classique", "biblique"]),
        fn(40, "Nora",      .female, "Latin",      "la",    "honneur, lumière", 2, 40, 34, ["lumiere"]),
        fn(41, "Lena",      .female, "Germanique", "de-DE", "lumière rayonnante", 2, 41, 113, ["lumiere"]),
        fn(42, "Hana",      .female, "Japonais",   "ja-JP", "fleur, bonheur", 2, 42, nil, ["nature", "fleur"]),
        fn(43, "Valentina", .female, "Latin",      "la",    "forte, saine", 4, 43, 162, ["force"]),
        fn(44, "Victoire",  .female, "Latin",      "la",    "victoire", 3, 44, nil, ["victoire"]),
        fn(45, "Céleste",   .female, "Latin",      "la",    "céleste, du ciel", 2, 45, 374, ["spirituel"]),
        fn(46, "Sirine",    .female, "Arabe",      "ar-SA", "sirène", 2, 46, nil, ["nature", "mer"]),
        fn(47, "Iris",      .female, "Grec",       "el-GR", "arc-en-ciel, iris", 2, 47, 151, ["nature", "fleur"]),
        fn(48, "Amina",     .female, "Arabe",      "ar-SA", "honnête, fiable", 3, 48, nil, ["vertu"]),
        fn(49, "Angèle",    .female, "Grec",       "el-GR", "messagère, ange", 2, 49, nil, ["spirituel"]),
        fn(50, "Maëlys",    .female, "Breton",     "br",    "lumière du prince", 3, 50, nil, ["lumiere"]),

        // ── French top 50 boys ────────────────────────────────────────────────
        fn(51, "Gabriel",   .male, "Hébreu",     "he-IL", "Dieu est ma force", 3, 1,  36, ["biblique", "force"]),
        fn(52, "Raphaël",   .male, "Hébreu",     "he-IL", "Dieu guérit", 3, 2,  nil, ["biblique"]),
        fn(53, "Léo",       .male, "Latin",      "la",    "lion", 2, 3,  53, ["force", "nature"]),
        fn(54, "Louis",     .male, "Germanique", "de-DE", "guerrier célèbre", 2, 4,  nil, ["classique", "force"]),
        fn(55, "Liam",      .male, "Irlandais",  "ga-IE", "volonté ferme, protection", 1, 5,  1,  ["force"]),
        fn(56, "Hugo",      .male, "Germanique", "de-DE", "intelligence, esprit", 2, 6,  nil, ["sagesse"]),
        fn(57, "Tom",       .male, "Araméen",    "arc",   "jumeau", 1, 7,  nil, ["classique"]),
        fn(58, "Théo",      .male, "Grec",       "el-GR", "don de Dieu", 2, 8,  nil, ["biblique"]),
        fn(59, "Nathan",    .male, "Hébreu",     "he-IL", "il a donné", 2, 9,  49, ["biblique"]),
        fn(60, "Adam",      .male, "Hébreu",     "he-IL", "homme de terre rouge", 2, 10, 13, ["biblique"]),
        fn(61, "Mathis",    .male, "Hébreu",     "he-IL", "don de Dieu", 2, 11, nil, ["biblique"]),
        fn(62, "Axel",      .male, "Hébreu",     "he-IL", "père de la paix", 2, 12, 116, ["paix"]),
        fn(63, "Ethan",     .male, "Hébreu",     "he-IL", "ferme, solide", 2, 13, 2,  ["force"]),
        fn(64, "Noah",      .male, "Hébreu",     "he-IL", "repos, réconfort", 2, 14, 3,  ["biblique"]),
        fn(65, "Lucas",     .male, "Grec",       "el-GR", "originaire de Lucanie", 2, 15, 5,  ["classique"]),
        fn(66, "Maxime",    .male, "Latin",      "la",    "le plus grand", 2, 16, nil, ["force"]),
        fn(67, "Arthur",    .male, "Celtique",   "cy",    "ours ou noble", 2, 17, nil, ["nature", "force"]),
        fn(68, "Jules",     .male, "Latin",      "la",    "de la gens Julia", 1, 18, nil, ["classique"]),
        fn(69, "Enzo",      .male, "Germanique", "de-DE", "maison, domaine", 2, 19, nil, ["classique"]),
        fn(70, "Clément",   .male, "Latin",      "la",    "doux, clément", 2, 20, nil, ["vertu"]),
        fn(71, "Oscar",     .male, "Nordique",   "no",    "lance divine", 2, 21, 89, ["force"]),
        fn(72, "Pierre",    .male, "Grec",       "el-GR", "pierre, roc", 1, 22, nil, ["classique"]),
        fn(73, "Paul",      .male, "Latin",      "la",    "petit, humble", 1, 23, nil, ["classique", "biblique"]),
        fn(74, "Simon",     .male, "Hébreu",     "he-IL", "il a entendu", 2, 24, 57, ["biblique"]),
        fn(75, "Antoine",   .male, "Latin",      "la",    "inestimable", 2, 25, nil, ["classique"]),
        fn(76, "Nicolas",   .male, "Grec",       "el-GR", "victoire du peuple", 3, 26, nil, ["victoire"]),
        fn(77, "Alexandre", .male, "Grec",       "el-GR", "défenseur des hommes", 4, 27, 29, ["force"]),
        fn(78, "Victor",    .male, "Latin",      "la",    "vainqueur", 2, 28, nil, ["victoire"]),
        fn(79, "Baptiste",  .male, "Grec",       "el-GR", "celui qui baptise", 2, 29, nil, ["biblique"]),
        fn(80, "Romain",    .male, "Latin",      "la",    "originaire de Rome", 2, 30, nil, ["classique"]),
        fn(81, "Florian",   .male, "Latin",      "la",    "qui fleurit", 3, 31, nil, ["nature", "fleur"]),
        fn(82, "Quentin",   .male, "Latin",      "la",    "cinquième", 2, 32, nil, ["classique"]),
        fn(83, "Bastien",   .male, "Grec",       "el-GR", "vénérable", 2, 33, nil, ["classique"]),
        fn(84, "Sébastien", .male, "Grec",       "el-GR", "vénérable", 3, 34, nil, ["classique"]),
        fn(85, "Valentin",  .male, "Latin",      "la",    "fort, sain", 3, 35, nil, ["force"]),
        fn(86, "Nolan",     .male, "Irlandais",  "ga-IE", "champion, noble", 2, 36, 45, ["force"]),
        fn(87, "Sacha",     .unisex, "Grec",     "el-GR", "protecteur des hommes", 2, 37, nil, ["force"]),
        fn(88, "Alexis",    .unisex, "Grec",     "el-GR", "défenseur", 3, 38, nil, ["force"]),
        fn(89, "Timothée",  .male, "Grec",       "el-GR", "qui honore Dieu", 3, 39, nil, ["biblique"]),
        fn(90, "Ilyan",     .male, "Hébreu",     "he-IL", "Dieu est le Seigneur", 3, 40, nil, ["biblique"]),
        fn(91, "Mattéo",    .male, "Hébreu",     "he-IL", "don de Dieu", 3, 41, nil, ["biblique"]),
        fn(92, "Luca",      .male, "Grec",       "el-GR", "lumière", 2, 42, nil, ["lumiere"]),
        fn(93, "Julien",    .male, "Latin",      "la",    "de la gens Julia", 3, 43, nil, ["classique"]),
        fn(94, "Tristan",   .male, "Celtique",   "br",    "tumulte, bruit", 2, 44, nil, ["force"]),
        fn(95, "Rémi",      .male, "Latin",      "la",    "rameur, aviron", 2, 45, nil, ["classique"]),
        fn(96, "Gauthier",  .male, "Germanique", "de-DE", "armée de gouvernement", 2, 46, nil, ["force"]),
        fn(97, "Loïc",      .male, "Breton",     "br",    "combattant glorieux", 2, 47, nil, ["force"]),
        fn(98, "Yann",      .male, "Hébreu",     "he-IL", "Dieu est gracieux", 1, 48, nil, ["biblique"]),
        fn(99, "Adrien",    .male, "Latin",      "la",    "originaire d'Adria", 3, 49, nil, ["classique"]),
        fn(100, "Dylan",    .male, "Gallois",    "cy",    "fils de la mer", 2, 50, 32, ["nature", "mer"]),

        // ── International / Hebrew ─────────────────────────────────────────────
        fn(101, "Mia",      .female, "Hébreu",   "he-IL", "aimée de Dieu", 2, nil, 8,  ["douceur"]),
        fn(102, "Elijah",   .male,   "Hébreu",   "he-IL", "mon Dieu est Yahvé", 3, nil, 4,  ["biblique"]),
        fn(103, "Hannah",   .female, "Hébreu",   "he-IL", "grâce", 2, nil, 33, ["biblique", "douceur"]),
        fn(104, "Samuel",   .male,   "Hébreu",   "he-IL", "son nom est Dieu", 2, nil, 20, ["biblique"]),
        fn(105, "Rachel",   .female, "Hébreu",   "he-IL", "brebis", 2, nil, nil, ["biblique"]),
        fn(106, "David",    .male,   "Hébreu",   "he-IL", "bien-aimé", 2, nil, nil, ["biblique"]),
        fn(107, "Naomi",    .female, "Hébreu",   "he-IL", "ma douceur, ma joie", 3, nil, 40, ["joie"]),
        fn(108, "Daniel",   .male,   "Hébreu",   "he-IL", "Dieu est mon juge", 3, nil, nil, ["biblique"]),
        fn(109, "Rebecca",  .female, "Hébreu",   "he-IL", "qui lie, qui captive", 3, nil, nil, ["biblique"]),
        fn(110, "Jonathan", .male,   "Hébreu",   "he-IL", "Dieu a donné", 3, nil, nil, ["biblique"]),

        // ── International / Greek ──────────────────────────────────────────────
        fn(111, "Athena",   .female, "Grec",     "el-GR", "sagesse divine", 3, nil, nil, ["sagesse", "mythologie"]),
        fn(112, "Phoebe",   .female, "Grec",     "el-GR", "lumineuse, brillante", 2, nil, 208, ["lumiere"]),
        fn(113, "Helena",   .female, "Grec",     "el-GR", "torche, lumière", 3, nil, nil, ["lumiere"]),
        fn(114, "Penelope",  .female, "Grec",    "el-GR", "tisseuse de toile", 4, nil, 24, ["litterature"]),
        fn(115, "Alexander", .male,  "Grec",     "el-GR", "défenseur des hommes", 4, nil, 8,  ["force"]),
        fn(116, "Theodore",  .male,  "Grec",     "el-GR", "don de Dieu", 4, nil, 10, ["biblique"]),
        fn(117, "Sebastian", .male,  "Grec",     "el-GR", "vénérable", 4, nil, 17, ["classique"]),
        fn(118, "Callista",  .female,"Grec",     "el-GR", "la plus belle", 3, nil, nil, ["beaute"]),
        fn(119, "Lysander",  .male,  "Grec",     "el-GR", "libérateur", 3, nil, nil, ["force"]),
        fn(120, "Corinna",   .female,"Grec",     "el-GR", "jeune fille", 3, nil, nil, ["classique"]),

        // ── International / Latin ──────────────────────────────────────────────
        fn(121, "Aurore",    .female,"Latin",    "la",    "aurore, aube", 2, nil, nil, ["nature", "lumiere"]),
        fn(122, "Fleur",     .female,"Latin",    "fr-FR", "fleur", 1, nil, nil, ["nature", "fleur"]),
        fn(123, "Maximus",   .male,  "Latin",    "la",    "le plus grand", 3, nil, nil, ["force"]),
        fn(124, "Felix",     .male,  "Latin",    "la",    "heureux, chanceux", 2, nil, 398, ["joie"]),
        fn(125, "Aurora",    .female,"Latin",    "la",    "aurore", 3, nil, 41, ["nature", "lumiere"]),
        fn(126, "Vivienne",  .female,"Latin",    "la",    "vivante", 3, nil, nil, ["vitalite"]),
        fn(127, "Lucian",    .male,  "Latin",    "la",    "lumière", 3, nil, nil, ["lumiere"]),
        fn(128, "Celestine", .female,"Latin",    "la",    "céleste", 3, nil, nil, ["spirituel"]),
        fn(129, "Julian",    .male,  "Latin",    "la",    "de la gens Julia", 3, nil, 34, ["classique"]),
        fn(130, "Valentina", .female,"Latin",    "la",    "forte, saine", 4, nil, 162, ["force"]),

        // ── Nordic / Scandinavian ──────────────────────────────────────────────
        fn(131, "Freya",    .female, "Nordique", "no",    "noble dame, déesse", 2, nil, 111, ["mythologie"]),
        fn(132, "Björn",    .male,   "Nordique", "sv-SE", "ours", 1, nil, nil, ["nature", "force"]),
        fn(133, "Sigrid",   .female, "Nordique", "sv-SE", "belle victoire", 2, nil, nil, ["victoire"]),
        fn(134, "Magnus",   .male,   "Nordique", "no",    "grand, puissant", 2, nil, nil, ["force"]),
        fn(135, "Astrid",   .female, "Nordique", "no",    "belle comme un dieu", 2, nil, nil, ["beaute"]),
        fn(136, "Leif",     .male,   "Nordique", "no",    "descendant, héritier", 1, nil, nil, ["classique"]),
        fn(137, "Ingrid",   .female, "Nordique", "no",    "belle Ing (dieu)", 2, nil, nil, ["beaute"]),
        fn(138, "Erik",     .male,   "Nordique", "sv-SE", "souverain éternel", 2, nil, nil, ["force"]),
        fn(139, "Signe",    .female, "Nordique", "sv-SE", "nouvelle victoire", 1, nil, nil, ["victoire"]),
        fn(140, "Gunnar",   .male,   "Nordique", "no",    "guerrier courageux", 2, nil, nil, ["force"]),

        // ── Celtic / Breton / Irish ────────────────────────────────────────────
        fn(141, "Maëlle",   .female, "Breton",   "br",    "princesse, chef", 2, nil, nil, ["classique"]),
        fn(142, "Erwan",    .male,   "Breton",   "br",    "if (arbre), noble", 2, nil, nil, ["nature"]),
        fn(143, "Gwenaëlle",.female, "Breton",   "br",    "blanche et bienheureuse", 3, nil, nil, ["pureté"]),
        fn(144, "Ronan",    .male,   "Breton",   "br",    "petit phoque", 2, nil, nil, ["nature"]),
        fn(145, "Aoife",    .female, "Irlandais","ga-IE", "radieuse, belle", 2, nil, nil, ["beaute"]),
        fn(146, "Ciarán",   .male,   "Irlandais","ga-IE", "foncé, sombre", 2, nil, nil, ["classique"]),
        fn(147, "Siobhán",  .female, "Irlandais","ga-IE", "Dieu est gracieux", 2, nil, nil, ["biblique"]),
        fn(148, "Tadhg",    .male,   "Irlandais","ga-IE", "poète, philosophe", 1, nil, nil, ["sagesse"]),
        fn(149, "Saoirse",  .female, "Irlandais","ga-IE", "liberté", 2, nil, nil, ["classique"]),
        fn(150, "Cormac",   .male,   "Irlandais","ga-IE", "fils du chariot", 2, nil, nil, ["classique"]),

        // ── Arabic / Islamic ───────────────────────────────────────────────────
        fn(151, "Yasmine",  .female, "Arabe",    "ar-SA", "fleur de jasmin", 2, nil, nil, ["nature", "fleur"]),
        fn(152, "Omar",     .male,   "Arabe",    "ar-SA", "vie longue, éloquent", 2, nil, nil, ["classique"]),
        fn(153, "Lina",     .female, "Arabe",    "ar-SA", "palmier ou tendre", 2, nil, nil, ["nature"]),
        fn(154, "Karim",    .male,   "Arabe",    "ar-SA", "généreux, noble", 2, nil, nil, ["vertu"]),
        fn(155, "Nour",     .unisex, "Arabe",    "ar-SA", "lumière", 1, nil, nil, ["lumiere"]),
        fn(156, "Amir",     .male,   "Arabe",    "ar-SA", "prince, commandant", 2, nil, nil, ["classique"]),
        fn(157, "Rania",    .female, "Arabe",    "ar-SA", "regarder avec les yeux", 2, nil, nil, ["beaute"]),
        fn(158, "Tariq",    .male,   "Arabe",    "ar-SA", "étoile du matin", 2, nil, nil, ["nature"]),
        fn(159, "Fatima",   .female, "Arabe",    "ar-SA", "qui sevrait, abstinente", 3, nil, nil, ["classique"]),
        fn(160, "Hamza",    .male,   "Arabe",    "ar-SA", "fort, ardent", 2, nil, nil, ["force"]),
        fn(161, "Leila",    .female, "Arabe",    "ar-SA", "nuit", 2, nil, nil, ["nature"]),
        fn(162, "Sami",     .male,   "Arabe",    "ar-SA", "élevé, exalté", 2, nil, nil, ["spirituel"]),
        fn(163, "Malak",    .female, "Arabe",    "ar-SA", "ange", 2, nil, nil, ["spirituel"]),
        fn(164, "Youssef",  .male,   "Hébreu",   "he-IL", "Dieu ajoutera", 2, nil, nil, ["biblique"]),
        fn(165, "Hiba",     .female, "Arabe",    "ar-SA", "don, cadeau", 2, nil, nil, ["joie"]),

        // ── Italian / Spanish ──────────────────────────────────────────────────
        fn(166, "Sofia",    .female, "Grec",     "el-GR", "sagesse", 3, nil, 2,  ["sagesse"]),
        fn(167, "Lorenzo",  .male,   "Latin",    "la",    "originaire de Laurent", 3, nil, nil, ["classique"]),
        fn(168, "Isabella", .female, "Hébreu",   "he-IL", "Dieu est ma promesse", 4, nil, 3,  ["biblique"]),
        fn(169, "Matteo",   .male,   "Hébreu",   "he-IL", "don de Dieu", 3, nil, nil, ["biblique"]),
        fn(170, "Chiara",   .female, "Latin",    "la",    "lumineuse, claire", 2, nil, nil, ["lumiere"]),
        fn(171, "Francesco",.male,   "Latin",    "la",    "originaire de France, libre", 3, nil, nil, ["classique"]),
        fn(172, "Lucia",    .female, "Latin",    "la",    "lumière", 3, nil, nil, ["lumiere"]),
        fn(173, "Marco",    .male,   "Latin",    "la",    "dieu Mars, guerrier", 2, nil, nil, ["force"]),
        fn(174, "Giulia",   .female, "Latin",    "la",    "de la gens Julia", 3, nil, nil, ["classique"]),
        fn(175, "Alejandro",.male,   "Grec",     "el-GR", "défenseur des hommes", 4, nil, nil, ["force"]),

        // ── Japanese ──────────────────────────────────────────────────────────
        fn(176, "Yuki",     .unisex, "Japonais", "ja-JP", "neige ou bonheur", 2, nil, nil, ["nature"]),
        fn(177, "Haruki",   .male,   "Japonais", "ja-JP", "printemps radieux", 3, nil, nil, ["nature"]),
        fn(178, "Sakura",   .female, "Japonais", "ja-JP", "fleur de cerisier", 3, nil, nil, ["nature", "fleur"]),
        fn(179, "Kenji",    .male,   "Japonais", "ja-JP", "enfant prudent et fort", 2, nil, nil, ["force", "sagesse"]),
        fn(180, "Akemi",    .female, "Japonais", "ja-JP", "belle clarté du matin", 3, nil, nil, ["lumiere", "beaute"]),
        fn(181, "Ryu",      .male,   "Japonais", "ja-JP", "dragon", 1, nil, nil, ["mythologie", "force"]),
        fn(182, "Aiko",     .female, "Japonais", "ja-JP", "enfant aimée", 3, nil, nil, ["douceur"]),
        fn(183, "Takeshi",  .male,   "Japonais", "ja-JP", "guerrier fort comme le bambou", 3, nil, nil, ["force"]),
        fn(184, "Yumi",     .female, "Japonais", "ja-JP", "beauté de l'arc, gracieuse", 2, nil, nil, ["beaute"]),
        fn(185, "Daiki",    .male,   "Japonais", "ja-JP", "grande gloire", 3, nil, nil, ["victoire"]),

        // ── English / Anglo-Saxon ──────────────────────────────────────────────
        fn(186, "Oliver",   .male,   "Latin",    "la",    "olivier, paix", 3, nil, 7,  ["nature", "paix"]),
        fn(187, "Olivia",   .female, "Latin",    "la",    "olivier", 4, nil, 5,  ["nature"]),
        fn(188, "William",  .male,   "Germanique","de-DE","volonté, protection", 3, nil, 6,  ["force"]),
        fn(189, "Ava",      .female, "Latin",    "la",    "vie", 2, nil, 6,  ["vitalite"]),
        fn(190, "James",    .male,   "Hébreu",   "he-IL", "qui supplante", 1, nil, 5,  ["classique"]),
        fn(191, "Charlotte",.female, "Germanique","de-DE","femme libre", 3, nil, 7,  ["classique"]),
        fn(192, "Benjamin", .male,   "Hébreu",   "he-IL", "fils de la main droite", 3, nil, 9,  ["biblique"]),
        fn(193, "Amelia",   .female, "Germanique","de-DE","travail", 4, nil, 4,  ["classique"]),
        fn(194, "Henry",    .male,   "Germanique","de-DE","seigneur de la maison", 2, nil, 11, ["classique"]),
        fn(195, "Harper",   .female, "Anglais",  "en-GB","harpiste", 2, nil, 10, ["art"]),

        // ── German ────────────────────────────────────────────────────────────
        fn(196, "Elsa",     .female, "Germanique","de-DE","Dieu est ma promesse", 2, nil, nil, ["biblique", "classique"]),
        fn(197, "Klaus",    .male,   "Grec",     "el-GR", "victoire du peuple", 1, nil, nil, ["victoire"]),
        fn(198, "Frieda",   .female, "Germanique","de-DE","paix", 2, nil, nil, ["paix"]),
        fn(199, "Hans",     .male,   "Hébreu",   "he-IL", "Dieu est gracieux", 1, nil, nil, ["biblique"]),
        fn(200, "Greta",    .female, "Grec",     "el-GR", "perle", 2, nil, nil, ["beaute"]),

        // ── Slavic / Eastern European ──────────────────────────────────────────
        fn(201, "Anastasia",.female, "Grec",     "el-GR", "résurrection", 4, nil, nil, ["spirituel"]),
        fn(202, "Ivan",     .male,   "Hébreu",   "he-IL", "Dieu est gracieux", 2, nil, nil, ["biblique"]),
        fn(203, "Katarina", .female, "Grec",     "el-GR", "pure", 4, nil, nil, ["pureté"]),
        fn(204, "Dmitri",   .male,   "Grec",     "el-GR", "dédié à Déméter", 3, nil, nil, ["mythologie"]),
        fn(205, "Natalia",  .female, "Latin",    "la",    "jour de Noël", 4, nil, nil, ["spirituel"]),
        fn(206, "Alexei",   .male,   "Grec",     "el-GR", "défenseur", 3, nil, nil, ["force"]),
        fn(207, "Oksana",   .female, "Ukrainien","uk-UA", "louange à Dieu", 3, nil, nil, ["spirituel"]),
        fn(208, "Bogdan",   .male,   "Slave",    "sr",    "don de Dieu", 2, nil, nil, ["biblique"]),
        fn(209, "Zoya",     .female, "Grec",     "el-GR", "la vie", 2, nil, nil, ["vitalite"]),
        fn(210, "Vasile",   .male,   "Grec",     "el-GR", "royal", 3, nil, nil, ["classique"]),

        // ── Indian / Sanskrit ─────────────────────────────────────────────────
        fn(211, "Priya",    .female, "Sanskrit", "hi-IN", "aimée, chère", 2, nil, nil, ["douceur"]),
        fn(212, "Arjun",    .male,   "Sanskrit", "hi-IN", "blanc, brillant", 2, nil, nil, ["lumiere"]),
        fn(213, "Ananya",   .female, "Sanskrit", "hi-IN", "unique, incomparable", 3, nil, nil, ["beaute"]),
        fn(214, "Rohan",    .male,   "Sanskrit", "hi-IN", "ascendant, croissant", 2, nil, nil, ["vitalite"]),
        fn(215, "Kavya",    .female, "Sanskrit", "hi-IN", "poème, poésie", 2, nil, nil, ["art"]),
        fn(216, "Vikram",   .male,   "Sanskrit", "hi-IN", "courageux, fort", 2, nil, nil, ["force"]),
        fn(217, "Diya",     .female, "Sanskrit", "hi-IN", "lumière, lampe", 2, nil, nil, ["lumiere"]),
        fn(218, "Aakash",   .male,   "Sanskrit", "hi-IN", "ciel, espace", 2, nil, nil, ["nature"]),
        fn(219, "Meera",    .female, "Sanskrit", "hi-IN", "mer, prospérité", 2, nil, nil, ["nature", "mer"]),
        fn(220, "Dhruv",    .male,   "Sanskrit", "hi-IN", "étoile polaire, constant", 1, nil, nil, ["nature"]),

        // ── African ────────────────────────────────────────────────────────────
        fn(221, "Amara",    .female, "Yoruba",   "yo",    "grâce, éternelle", 3, nil, nil, ["douceur"]),
        fn(222, "Kofi",     .male,   "Akan",     "ak",    "né un vendredi", 2, nil, nil, ["classique"]),
        fn(223, "Imani",    .female, "Swahili",  "sw",    "foi, croyance", 3, nil, nil, ["spirituel"]),
        fn(224, "Kwame",    .male,   "Akan",     "ak",    "né un samedi", 2, nil, nil, ["classique"]),
        fn(225, "Zara",     .female, "Arabe",    "ar-SA", "fleur épanouie", 2, nil, 133, ["nature", "fleur"]),
        fn(226, "Jabari",   .male,   "Swahili",  "sw",    "courageux, brave", 3, nil, nil, ["force"]),
        fn(227, "Nia",      .female, "Swahili",  "sw",    "but, intention", 2, nil, nil, ["sagesse"]),
        fn(228, "Chukwu",   .male,   "Igbo",     "ig",    "Dieu suprême", 2, nil, nil, ["spirituel"]),
        fn(229, "Adaeze",   .female, "Igbo",     "ig",    "fille du roi", 3, nil, nil, ["classique"]),
        fn(230, "Seun",     .male,   "Yoruba",   "yo",    "récompense, bénédiction", 1, nil, nil, ["joie"]),

        // ── Portuguese / Brazilian ─────────────────────────────────────────────
        fn(231, "Beatriz",  .female, "Latin",    "la",    "bienheureuse, heureuse", 3, nil, nil, ["joie"]),
        fn(232, "Pedro",    .male,   "Grec",     "el-GR", "pierre, roc", 2, nil, nil, ["classique"]),
        fn(233, "Mariana",  .female, "Latin",    "la",    "de la mer, grâce", 4, nil, nil, ["nature", "mer"]),
        fn(234, "Eduardo",  .male,   "Germanique","de-DE","gardien des richesses", 4, nil, nil, ["force"]),
        fn(235, "Isabela",  .female, "Hébreu",   "he-IL", "Dieu est ma promesse", 4, nil, nil, ["biblique"]),

        // ── Turkish / Central Asian ────────────────────────────────────────────
        fn(236, "Ayşe",     .female, "Arabe",    "ar-SA", "vivante, prospère", 2, nil, nil, ["vitalite"]),
        fn(237, "Mehmet",   .male,   "Arabe",    "ar-SA", "digne de louange", 2, nil, nil, ["spirituel"]),
        fn(238, "Fatima",   .female, "Arabe",    "ar-SA", "qui sevrait", 3, nil, nil, ["classique"]),
        fn(239, "Ali",      .male,   "Arabe",    "ar-SA", "élevé, noble", 2, nil, nil, ["classique"]),
        fn(240, "Zeynep",   .female, "Arabe",    "ar-SA", "trésor du père", 2, nil, nil, ["classique"]),

        // ── Additional French classics & modern ────────────────────────────────
        fn(241, "Maël",     .male,   "Breton",   "br",    "prince, chef", 1, nil, nil, ["classique"]),
        fn(242, "Loane",    .female, "Breton",   "br",    "lumière", 2, nil, nil, ["lumiere"]),
        fn(243, "Gaspard",  .male,   "Perse",    "fa-IR", "gardien du trésor", 2, nil, nil, ["classique"]),
        fn(244, "Honorine", .female, "Latin",    "la",    "honorable", 3, nil, nil, ["vertu"]),
        fn(245, "Augustin", .male,   "Latin",    "la",    "vénérable, majestueux", 3, nil, nil, ["classique"]),
        fn(246, "Apolline", .female, "Grec",     "el-GR", "d'Apollon, solaire", 3, nil, nil, ["mythologie", "lumiere"]),
        fn(247, "Thibault", .male,   "Germanique","de-DE","peuple audacieux", 2, nil, nil, ["force"]),
        fn(248, "Aliénor",  .female, "Occitan",  "oc",    "autre Éléonore", 3, nil, nil, ["classique"]),
        fn(249, "Eudes",    .male,   "Germanique","de-DE","richesse, fortune", 1, nil, nil, ["classique"]),
        fn(250, "Hortense", .female, "Latin",    "la",    "du jardin", 2, nil, nil, ["nature"]),

        fn(251, "Madeleine",.female, "Hébreu",   "he-IL", "de Magdala, tour", 3, nil, nil, ["classique", "biblique"]),
        fn(252, "Edouard",  .male,   "Germanique","de-DE","gardien des richesses", 3, nil, nil, ["classique"]),
        fn(253, "Thérèse",  .female, "Grec",     "el-GR", "chasseresse, moissonneusse", 2, nil, nil, ["classique"]),
        fn(254, "Fernand",  .male,   "Germanique","de-DE","voyage audacieux", 2, nil, nil, ["classique"]),
        fn(255, "Colette",  .female, "Latin",    "la",    "victoire du peuple", 2, nil, nil, ["victoire"]),
        fn(256, "Marcel",   .male,   "Latin",    "la",    "petit marteau, de Mars", 2, nil, nil, ["classique"]),
        fn(257, "Solange",  .female, "Latin",    "la",    "sacrée, solennelle", 2, nil, nil, ["spirituel"]),
        fn(258, "Gaston",   .male,   "Germanique","de-DE","hôte, étranger", 2, nil, nil, ["classique"]),
        fn(259, "Bernadette",.female,"Germanique","de-DE","ours courageux", 4, nil, nil, ["force", "nature"]),
        fn(260, "Fernande", .female, "Germanique","de-DE","voyage audacieux", 2, nil, nil, ["classique"]),

        fn(261, "Anatole",  .male,   "Grec",     "el-GR", "levant, orient", 3, nil, nil, ["nature"]),
        fn(262, "Blanche",  .female, "Germanique","de-DE","blanc, pur", 1, nil, nil, ["pureté"]),
        fn(263, "Cyprien",  .male,   "Grec",     "el-GR", "originaire de Chypre", 3, nil, nil, ["classique"]),
        fn(264, "Delphine", .female, "Latin",    "la",    "dauphin", 2, nil, nil, ["nature", "mer"]),
        fn(265, "Evariste", .male,   "Grec",     "el-GR", "le bon", 3, nil, nil, ["vertu"]),
        fn(266, "Flavie",   .female, "Latin",    "la",    "blonde, or", 2, nil, nil, ["nature"]),
        fn(267, "Gonzague", .male,   "Basque",   "eu",    "combat, guerre", 2, nil, nil, ["force"]),
        fn(268, "Héloïse",  .female, "Germanique","de-DE","santé, guerrière", 3, nil, nil, ["force", "litterature"]),
        fn(269, "Isidore",  .male,   "Grec",     "el-GR", "don d'Isis", 3, nil, nil, ["mythologie"]),
        fn(270, "Joséphine",.female, "Hébreu",   "he-IL", "Dieu ajoutera", 3, nil, nil, ["biblique", "classique"]),

        // ── Nature-themed ──────────────────────────────────────────────────────
        fn(271, "Aurelia",  .female, "Latin",    "la",    "dorée", 4, nil, nil, ["nature", "lumiere"]),
        fn(272, "Forêt",    .male,   "Latin",    "la",    "forêt, sylvestre", 2, nil, nil, ["nature"]),
        fn(273, "Marina",   .female, "Latin",    "la",    "de la mer", 3, nil, nil, ["nature", "mer"]),
        fn(274, "Sylvain",  .male,   "Latin",    "la",    "de la forêt", 2, nil, nil, ["nature"]),
        fn(275, "Violette", .female, "Latin",    "la",    "violette", 3, nil, nil, ["nature", "fleur"]),
        fn(276, "Gaïa",     .female, "Grec",     "el-GR", "Terre mère", 2, nil, nil, ["nature", "mythologie"]),
        fn(277, "Orion",    .male,   "Grec",     "el-GR", "chasseur céleste", 3, nil, nil, ["mythologie", "nature"]),
        fn(278, "Solène",   .female, "Latin",    "la",    "solennelle, sacrée", 2, nil, nil, ["spirituel"]),
        fn(279, "Sylvio",   .male,   "Latin",    "la",    "sylvestre, forêt", 3, nil, nil, ["nature"]),
        fn(280, "Flore",    .female, "Latin",    "la",    "fleur", 1, nil, nil, ["nature", "fleur"]),

        // ── Mythological ──────────────────────────────────────────────────────
        fn(281, "Achille",  .male,   "Grec",     "el-GR", "douleur du peuple", 2, nil, nil, ["mythologie", "force"]),
        fn(282, "Cassandre",.female, "Grec",     "el-GR", "qui brille sur les hommes", 3, nil, nil, ["mythologie"]),
        fn(283, "Héros",    .male,   "Grec",     "el-GR", "protecteur", 2, nil, nil, ["mythologie", "force"]),
        fn(284, "Diane",    .female, "Latin",    "la",    "divine, lumière", 2, nil, nil, ["mythologie", "lumiere"]),
        fn(285, "Vulcain",  .male,   "Latin",    "la",    "feu, forge", 2, nil, nil, ["mythologie"]),
        fn(286, "Calypso",  .female, "Grec",     "el-GR", "celle qui cache", 3, nil, nil, ["mythologie"]),
        fn(287, "Odyssée",  .male,   "Grec",     "el-GR", "voyage, errance", 3, nil, nil, ["mythologie"]),
        fn(288, "Aphrodite",.female, "Grec",     "el-GR", "née de l'écume", 4, nil, nil, ["mythologie", "beaute"]),
        fn(289, "Ajax",     .male,   "Grec",     "el-GR", "deuil de la terre", 2, nil, nil, ["mythologie", "force"]),
        fn(290, "Perséphone",.female,"Grec",     "el-GR", "celle qui apporte la destruction", 4, nil, nil, ["mythologie"]),

        // ── Light / Brightness themed ──────────────────────────────────────────
        fn(291, "Lucine",   .female, "Latin",    "la",    "lumière, lune", 2, nil, nil, ["lumiere"]),
        fn(292, "Élodie",   .female, "Grec",     "el-GR", "étrangère, pèlerine", 3, nil, nil, ["classique"]),
        fn(293, "Cyprine",  .female, "Grec",     "el-GR", "de Chypre, cuivre", 2, nil, nil, ["classique"]),
        fn(294, "Lucio",    .male,   "Latin",    "la",    "lumière", 3, nil, nil, ["lumiere"]),
        fn(295, "Élia",     .female, "Hébreu",   "he-IL", "Dieu est le Seigneur", 3, nil, nil, ["biblique"]),
        fn(296, "Philibert",.male,   "Germanique","de-DE","très illustre", 3, nil, nil, ["classique"]),
        fn(297, "Léonore",  .female, "Grec",     "el-GR", "lumière de compassion", 3, nil, nil, ["lumiere"]),
        fn(298, "Apollinaire",.male, "Grec",     "el-GR", "d'Apollon", 4, nil, nil, ["mythologie"]),
        fn(299, "Clarisse", .female, "Latin",    "la",    "lumineuse, illustre", 2, nil, nil, ["lumiere"]),
        fn(300, "Séraphin", .male,   "Hébreu",   "he-IL", "ardent, enflammé", 3, nil, nil, ["spirituel"]),

        // ── Virtue themed ──────────────────────────────────────────────────────
        fn(301, "Prudence", .female, "Latin",    "la",    "prudence, sagesse", 2, nil, nil, ["sagesse", "vertu"]),
        fn(302, "Patience", .female, "Latin",    "la",    "patience, endurance", 3, nil, nil, ["vertu"]),
        fn(303, "Espérance",.female, "Latin",    "la",    "espoir", 3, nil, nil, ["vertu"]),
        fn(304, "Constance",.female, "Latin",    "la",    "constante, ferme", 2, nil, nil, ["vertu", "force"]),
        fn(305, "Vertu",    .female, "Latin",    "la",    "excellence morale", 2, nil, nil, ["vertu"]),
        fn(306, "Amour",    .male,   "Latin",    "la",    "amour", 2, nil, nil, ["douceur"]),
        fn(307, "Fidèle",   .male,   "Latin",    "la",    "fidèle, loyal", 2, nil, nil, ["vertu"]),
        fn(308, "Modeste",  .male,   "Latin",    "la",    "modéré, retenu", 2, nil, nil, ["vertu"]),
        fn(309, "Joie",     .female, "Latin",    "la",    "joie", 1, nil, nil, ["joie"]),
        fn(310, "Paix",     .female, "Latin",    "la",    "paix", 1, nil, nil, ["paix"]),

        // ── Korean ─────────────────────────────────────────────────────────────
        fn(311, "Ji-ho",    .unisex, "Coréen",   "ko-KR", "intelligence et bonté", 2, nil, nil, ["sagesse"]),
        fn(312, "Min-jun",  .male,   "Coréen",   "ko-KR", "brillant et talentueux", 2, nil, nil, ["sagesse"]),
        fn(313, "Soo-yeon", .female, "Coréen",   "ko-KR", "élégante et gracieuse", 3, nil, nil, ["beaute"]),
        fn(314, "Hyun-woo", .male,   "Coréen",   "ko-KR", "sage et exceptionnel", 3, nil, nil, ["sagesse"]),
        fn(315, "Ye-jin",   .female, "Coréen",   "ko-KR", "belle et précieuse", 3, nil, nil, ["beaute"]),

        // ── Chinese ────────────────────────────────────────────────────────────
        fn(316, "Wei",      .male,   "Chinois",  "zh-CN", "grand, imposant", 1, nil, nil, ["force"]),
        fn(317, "Mei",      .female, "Chinois",  "zh-CN", "belle, gracieuse", 1, nil, nil, ["beaute"]),
        fn(318, "Fang",     .female, "Chinois",  "zh-CN", "parfum, fleur", 1, nil, nil, ["nature", "fleur"]),
        fn(319, "Jie",      .male,   "Chinois",  "zh-CN", "pur, excellent", 1, nil, nil, ["pureté"]),
        fn(320, "Xin",      .female, "Chinois",  "zh-CN", "nouveau, coeur", 1, nil, nil, ["douceur"]),

        // ── Additional Modern French ───────────────────────────────────────────
        fn(321, "Tiago",    .male,   "Hébreu",   "he-IL", "qui supplante", 3, nil, nil, ["classique"]),
        fn(322, "Lena",     .female, "Grec",     "el-GR", "lumière du soleil", 2, nil, nil, ["lumiere"]),
        fn(323, "Maxence",  .male,   "Latin",    "la",    "le plus grand", 2, nil, nil, ["force"]),
        fn(324, "Sixtine",  .female, "Latin",    "la",    "sixième", 2, nil, nil, ["classique"]),
        fn(325, "Côme",     .male,   "Grec",     "el-GR", "ordre, beauté", 1, nil, nil, ["beaute"]),
        fn(326, "Romane",   .female, "Latin",    "la",    "originaire de Rome", 2, nil, nil, ["classique"]),
        fn(327, "Lazare",   .male,   "Hébreu",   "he-IL", "Dieu a aidé", 2, nil, nil, ["biblique"]),
        fn(328, "Céleste",  .male,   "Latin",    "la",    "céleste, du ciel", 2, nil, nil, ["spirituel"]),
        fn(329, "Léontine", .female, "Latin",    "la",    "lion, courageuse", 3, nil, nil, ["force", "nature"]),
        fn(330, "Baudouin", .male,   "Germanique","de-DE","ami audacieux", 2, nil, nil, ["force"]),

        fn(331, "Ondine",   .female, "Latin",    "la",    "petite onde, eau", 2, nil, nil, ["nature", "mer"]),
        fn(332, "Hippolyte",.male,   "Grec",     "el-GR", "qui libère les chevaux", 3, nil, nil, ["mythologie"]),
        fn(333, "Flavia",   .female, "Latin",    "la",    "blonde, or", 3, nil, nil, ["nature"]),
        fn(334, "Désiré",   .male,   "Latin",    "la",    "désiré, attendu", 3, nil, nil, ["classique"]),
        fn(335, "Geneviève",.female, "Celtique", "br",    "blanche de race", 3, nil, nil, ["classique"]),
        fn(336, "Gilles",   .male,   "Grec",     "el-GR", "chevreau", 1, nil, nil, ["nature"]),
        fn(337, "Hermione", .female, "Grec",     "el-GR", "messagère", 3, nil, nil, ["mythologie", "litterature"]),
        fn(338, "Ignace",   .male,   "Latin",    "la",    "ardent, de feu", 2, nil, nil, ["spirituel"]),
        fn(339, "Jessamine",.female, "Perse",    "fa-IR", "jasmin", 3, nil, nil, ["nature", "fleur"]),
        fn(340, "Killian",  .male,   "Irlandais","ga-IE", "petit guerrier", 3, nil, nil, ["force"]),

        fn(341, "Lison",    .female, "Hébreu",   "he-IL", "Dieu est ma promesse", 2, nil, nil, ["biblique"]),
        fn(342, "Malo",     .male,   "Breton",   "br",    "brillant prince", 2, nil, nil, ["classique"]),
        fn(343, "Ninon",    .female, "Hébreu",   "he-IL", "grâce divine", 2, nil, nil, ["douceur"]),
        fn(344, "Oskar",    .male,   "Nordique", "no",    "lance divine", 2, nil, nil, ["force"]),
        fn(345, "Perrine",  .female, "Grec",     "el-GR", "pierre, roc", 2, nil, nil, ["classique"]),
        fn(346, "Quentin",  .male,   "Latin",    "la",    "cinquième", 2, nil, nil, ["classique"]),
        fn(347, "Rosalie",  .female, "Latin",    "la",    "rose", 3, nil, nil, ["nature", "fleur"]),
        fn(348, "Stanislas",.male,   "Slave",    "pl",    "gloire stable", 3, nil, nil, ["victoire"]),
        fn(349, "Tiphaine", .female, "Grec",     "el-GR", "manifestation divine", 2, nil, nil, ["spirituel"]),
        fn(350, "Ulysse",   .male,   "Grec",     "el-GR", "courroux, voyage", 2, nil, nil, ["mythologie"]),

        fn(351, "Violaine",  .female,"Latin",    "la",    "violette", 3, nil, nil, ["nature", "fleur"]),
        fn(352, "Wandrille", .male,  "Germanique","de-DE","chemin de la gloire", 2, nil, nil, ["classique"]),
        fn(353, "Xavière",  .female, "Basque",   "eu",    "nouvelle maison", 3, nil, nil, ["classique"]),
        fn(354, "Yolande",  .female, "Germanique","de-DE","vive, ardente", 3, nil, nil, ["vitalite"]),
        fn(355, "Zacharie", .male,   "Hébreu",   "he-IL", "Dieu se souvient", 3, nil, nil, ["biblique"]),
        fn(356, "Abigaïl",  .female, "Hébreu",   "he-IL", "joie du père", 3, nil, nil, ["joie", "biblique"]),
        fn(357, "Balthazar",.male,   "Phénicien","arc",   "protège le roi", 3, nil, nil, ["classique"]),
        fn(358, "Capucine", .female, "Latin",    "la",    "capucine (fleur)", 3, nil, nil, ["nature", "fleur"]),
        fn(359, "Donatien", .male,   "Latin",    "la",    "don de Dieu", 3, nil, nil, ["biblique"]),
        fn(360, "Eulalie",  .female, "Grec",     "el-GR", "qui parle bien", 3, nil, nil, ["art"]),

        fn(361, "Fiacre",   .male,   "Irlandais","ga-IE", "aigle de combat", 2, nil, nil, ["force"]),
        fn(362, "Guillemette",.female,"Germanique","de-DE","volonté, protection", 3, nil, nil, ["force"]),
        fn(363, "Hadrien",  .male,   "Latin",    "la",    "originaire d'Adria", 3, nil, nil, ["classique"]),
        fn(364, "Isaure",   .female, "Grec",     "el-GR", "originaire d'Isaure", 2, nil, nil, ["classique"]),
        fn(365, "Jourdain", .male,   "Hébreu",   "he-IL", "qui descend, fleuve", 2, nil, nil, ["nature", "mer"]),
        fn(366, "Lorraine", .female, "Latin",    "la",    "de Lorraine", 2, nil, nil, ["classique"]),
        fn(367, "Mathieu",  .male,   "Hébreu",   "he-IL", "don de Dieu", 3, nil, nil, ["biblique"]),
        fn(368, "Narcisse", .male,   "Grec",     "el-GR", "engourdissement", 2, nil, nil, ["mythologie"]),
        fn(369, "Olympe",   .female, "Grec",     "el-GR", "du mont Olympe", 2, nil, nil, ["mythologie"]),
        fn(370, "Philibert",.male,   "Germanique","de-DE","très illustre", 3, nil, nil, ["classique"]),

        fn(371, "Rosalinde",.female, "Germanique","de-DE","tendre comme le cheval", 3, nil, nil, ["nature"]),
        fn(372, "Séverin",  .male,   "Latin",    "la",    "sévère, rigoureux", 3, nil, nil, ["classique"]),
        fn(373, "Théodore", .male,   "Grec",     "el-GR", "don de Dieu", 3, nil, nil, ["biblique"]),
        fn(374, "Ursula",   .female, "Latin",    "la",    "petite ourse", 3, nil, nil, ["nature"]),
        fn(375, "Viviane",  .female, "Latin",    "la",    "vivante", 3, nil, nil, ["vitalite"]),
        fn(376, "Aldric",   .male,   "Germanique","de-DE","noble souverain", 2, nil, nil, ["classique"]),
        fn(377, "Bérengère",.female, "Germanique","de-DE","ours protecteur", 3, nil, nil, ["force", "nature"]),
        fn(378, "Corentin", .male,   "Breton",   "br",    "ami", 3, nil, nil, ["classique"]),
        fn(379, "Dorothée", .female, "Grec",     "el-GR", "don de Dieu", 3, nil, nil, ["biblique"]),
        fn(380, "Edwige",   .female, "Germanique","de-DE","combat heureux", 2, nil, nil, ["force"]),

        fn(381, "Félicien", .male,   "Latin",    "la",    "heureux, chanceux", 3, nil, nil, ["joie"]),
        fn(382, "Gauderique",.male,  "Latin",    "la",    "joyeux", 3, nil, nil, ["joie"]),
        fn(383, "Hypatie",  .female, "Grec",     "el-GR", "la plus haute", 3, nil, nil, ["sagesse"]),
        fn(384, "Ismaël",   .male,   "Hébreu",   "he-IL", "Dieu entend", 3, nil, nil, ["biblique"]),
        fn(385, "Jocaste",  .female, "Grec",     "el-GR", "brillante lune", 3, nil, nil, ["mythologie"]),
        fn(386, "Kilian",   .male,   "Irlandais","ga-IE", "petit guerrier", 3, nil, nil, ["force"]),
        fn(387, "Léa",      .female, "Hébreu",   "he-IL", "fatiguée", 2, nil, nil, ["biblique"]),
        fn(388, "Mélusine", .female, "Latin",    "la",    "fée des eaux", 3, nil, nil, ["mythologie", "mer"]),
        fn(389, "Nathalie", .female, "Latin",    "la",    "jour de Noël", 3, nil, nil, ["spirituel"]),
        fn(390, "Odilon",   .male,   "Germanique","de-DE","richesse et combat", 3, nil, nil, ["force"]),

        fn(391, "Pénélope", .female, "Grec",     "el-GR", "tisseuse de toile", 4, nil, nil, ["litterature"]),
        fn(392, "Quendrida",.female, "Germanique","de-DE","cheval et force", 3, nil, nil, ["force"]),
        fn(393, "Réginald", .male,   "Germanique","de-DE","conseiller du roi", 3, nil, nil, ["classique"]),
        fn(394, "Séverine", .female, "Latin",    "la",    "sévère, rigoureuse", 3, nil, nil, ["classique"]),
        fn(395, "Timoléon", .male,   "Grec",     "el-GR", "qui honore le peuple", 3, nil, nil, ["classique"]),
        fn(396, "Ursule",   .female, "Latin",    "la",    "petite ourse", 2, nil, nil, ["nature"]),
        fn(397, "Véronique",.female, "Grec",     "el-GR", "vraie image", 3, nil, nil, ["classique"]),
        fn(398, "Wilfried", .male,   "Germanique","de-DE","désir de paix", 2, nil, nil, ["paix"]),
        fn(399, "Xanthippe",.female, "Grec",     "el-GR", "cheval blond", 3, nil, nil, ["classique"]),
        fn(400, "Yolène",   .female, "Germanique","de-DE","arc, violette", 3, nil, nil, ["nature", "fleur"]),

        fn(401, "Zenon",    .male,   "Grec",     "el-GR", "de Zeus, céleste", 2, nil, nil, ["mythologie"]),
        fn(402, "Ariane",   .female, "Grec",     "el-GR", "très sainte", 3, nil, nil, ["mythologie"]),
        fn(403, "Barnabé",  .male,   "Hébreu",   "he-IL", "fils de consolation", 3, nil, nil, ["biblique"]),
        fn(404, "Candice",  .female, "Latin",    "la",    "pure, brillante", 2, nil, nil, ["pureté"]),
        fn(405, "Dagobert", .male,   "Germanique","de-DE","brillant jour", 3, nil, nil, ["classique"]),
        fn(406, "Emeraude", .female, "Latin",    "la",    "émeraude (pierre)", 3, nil, nil, ["nature", "mineral"]),
        fn(407, "Fabrice",  .male,   "Latin",    "la",    "artisan, forgeron", 2, nil, nil, ["classique"]),
        fn(408, "Gabrielle",.female, "Hébreu",   "he-IL", "Dieu est ma force", 3, nil, nil, ["biblique", "force"]),
        fn(409, "Humbert",  .male,   "Germanique","de-DE","géant lumineux", 2, nil, nil, ["lumiere"]),
        fn(410, "Ingeborg", .female, "Nordique", "no",    "gardée par Ing (dieu)", 3, nil, nil, ["classique"]),

        fn(411, "Jacqueline",.female,"Hébreu",   "he-IL", "qui supplante", 3, nil, nil, ["classique"]),
        fn(412, "Kléber",   .male,   "Germanique","de-DE","chambre, espace clos", 2, nil, nil, ["classique"]),
        fn(413, "Ludivine", .female, "Germanique","de-DE","lumière du peuple", 3, nil, nil, ["lumiere"]),
        fn(414, "Modeste",  .male,   "Latin",    "la",    "modéré, retenu", 2, nil, nil, ["vertu"]),
        fn(415, "Narcissa", .female, "Grec",     "el-GR", "engourdissement", 3, nil, nil, ["mythologie"]),
        fn(416, "Octave",   .male,   "Latin",    "la",    "huitième", 2, nil, nil, ["classique"]),
        fn(417, "Pélagie",  .female, "Grec",     "el-GR", "de la mer", 3, nil, nil, ["nature", "mer"]),
        fn(418, "Quirinus", .male,   "Latin",    "la",    "lance, guerrier", 3, nil, nil, ["force"]),
        fn(419, "Régine",   .female, "Latin",    "la",    "reine", 2, nil, nil, ["classique"]),
        fn(420, "Sidonie",  .female, "Latin",    "la",    "originaire de Sidon", 3, nil, nil, ["classique"]),

        fn(421, "Théodosie",.female, "Grec",     "el-GR", "don de Dieu", 4, nil, nil, ["biblique"]),
        fn(422, "Urbain",   .male,   "Latin",    "la",    "de la ville", 2, nil, nil, ["classique"]),
        fn(423, "Valentine",.female, "Latin",    "la",    "forte, saine", 3, nil, nil, ["force"]),
        fn(424, "Wilfrid",  .male,   "Germanique","de-DE","désir de paix", 2, nil, nil, ["paix"]),
        fn(425, "Xavière",  .female, "Basque",   "eu",    "maison neuve", 2, nil, nil, ["classique"]),
        fn(426, "Yves",     .male,   "Celtique", "br",    "if (arbre)", 1, nil, nil, ["nature"]),
        fn(427, "Zoélie",   .female, "Grec",     "el-GR", "la vie", 3, nil, nil, ["vitalite"]),
        fn(428, "Alaric",   .male,   "Germanique","de-DE","roi de tous", 3, nil, nil, ["classique"]),
        fn(429, "Béatrice", .female, "Latin",    "la",    "bienheureuse", 3, nil, nil, ["joie", "classique"]),
        fn(430, "Cécile",   .female, "Latin",    "la",    "aveugle (sainte)", 2, nil, nil, ["classique"]),

        fn(431, "Damien",   .male,   "Grec",     "el-GR", "qui dompte, maîtrise", 3, nil, nil, ["force"]),
        fn(432, "Eléonore", .female, "Occitan",  "oc",    "autre Hélène", 4, nil, nil, ["classique"]),
        fn(433, "Fulgence", .male,   "Latin",    "la",    "brillant, éclatant", 2, nil, nil, ["lumiere"]),
        fn(434, "Gervais",  .male,   "Germanique","de-DE","lance étincelante", 2, nil, nil, ["force"]),
        fn(435, "Hildegarde",.female,"Germanique","de-DE","battle enclosure", 3, nil, nil, ["force", "sagesse"]),
        fn(436, "Imelda",   .female, "Germanique","de-DE","combat universel", 3, nil, nil, ["force"]),
        fn(437, "Jérémie",  .male,   "Hébreu",   "he-IL", "Dieu exaltera", 3, nil, nil, ["biblique"]),
        fn(438, "Korentin", .male,   "Breton",   "br",    "ami", 3, nil, nil, ["classique"]),
        fn(439, "Laetitia", .female, "Latin",    "la",    "joie, gaîté", 4, nil, nil, ["joie"]),
        fn(440, "Melchior", .male,   "Hébreu",   "he-IL", "roi de lumière", 3, nil, nil, ["lumiere"]),

        fn(441, "Nectaire", .male,   "Grec",     "el-GR", "nectar divin", 3, nil, nil, ["spirituel"]),
        fn(442, "Ophelie",  .female, "Grec",     "el-GR", "aide, secours", 3, nil, nil, ["litterature"]),
        fn(443, "Placide",  .male,   "Latin",    "la",    "calme, tranquille", 2, nil, nil, ["paix"]),
        fn(444, "Quillan",  .male,   "Irlandais","ga-IE", "cub of the holly", 2, nil, nil, ["nature"]),
        fn(445, "Rosamund", .female, "Germanique","de-DE","cheval pur", 3, nil, nil, ["nature"]),
        fn(446, "Stéphanie",.female, "Grec",     "el-GR", "couronnée", 3, nil, nil, ["victoire"]),
        fn(447, "Tancrede", .male,   "Normand",  "nrf",   "pensée de conseil", 2, nil, nil, ["sagesse"]),
        fn(448, "Ulrica",   .female, "Germanique","de-DE","souveraine des loups", 3, nil, nil, ["nature", "force"]),
        fn(449, "Véronique",.female, "Grec",     "el-GR", "vraie image", 3, nil, nil, ["classique"]),
        fn(450, "Wenceslas",.male,   "Slave",    "cs",    "grande gloire", 3, nil, nil, ["victoire"]),

        fn(451, "Xénophon", .male,   "Grec",     "el-GR", "voix étrangère", 3, nil, nil, ["classique"]),
        fn(452, "Yvonne",   .female, "Germanique","de-DE","if (arbre)", 2, nil, nil, ["nature"]),
        fn(453, "Zéphyrin", .male,   "Grec",     "el-GR", "zéphyr, vent d'ouest", 3, nil, nil, ["nature"]),
        fn(454, "Aldéric",  .male,   "Germanique","de-DE","noble souverain", 3, nil, nil, ["classique"]),
        fn(455, "Blandine", .female, "Latin",    "la",    "douce, agréable", 2, nil, nil, ["douceur"]),
        fn(456, "Corneille",.male,   "Latin",    "la",    "corne", 3, nil, nil, ["classique"]),
        fn(457, "Désirée",  .female, "Latin",    "la",    "désirée, attendue", 3, nil, nil, ["classique"]),
        fn(458, "Epiphane", .male,   "Grec",     "el-GR", "brillant, illustre", 3, nil, nil, ["lumiere"]),
        fn(459, "Florentine",.female,"Latin",    "la",    "qui fleurit", 3, nil, nil, ["nature", "fleur"]),
        fn(460, "Gebhard",  .male,   "Germanique","de-DE","don valeureux", 2, nil, nil, ["classique"]),

        fn(461, "Hilarion", .male,   "Grec",     "el-GR", "gai, joyeux", 3, nil, nil, ["joie"]),
        fn(462, "Idunn",    .female, "Nordique", "no",    "renaissance", 2, nil, nil, ["mythologie", "vitalite"]),
        fn(463, "Josèphe",  .female, "Hébreu",   "he-IL", "Dieu ajoutera", 2, nil, nil, ["biblique"]),
        fn(464, "Landry",   .male,   "Germanique","de-DE","propriétaire terrien", 2, nil, nil, ["classique"]),
        fn(465, "Marceline",.female, "Latin",    "la",    "de Mars, guerrière", 3, nil, nil, ["force"]),
        fn(466, "Nemo",     .male,   "Latin",    "la",    "personne, nul, sous-marin", 2, nil, nil, ["litterature"]),
        fn(467, "Orsolya",  .female, "Latin",    "la",    "petite ourse", 3, nil, nil, ["nature"]),
        fn(468, "Pâris",    .male,   "Grec",     "el-GR", "ville des Parisii", 2, nil, nil, ["mythologie"]),
        fn(469, "Quiriace", .male,   "Grec",     "el-GR", "dominical", 3, nil, nil, ["spirituel"]),
        fn(470, "Rodoald",  .male,   "Germanique","de-DE","gloire et force", 3, nil, nil, ["victoire"]),

        fn(471, "Séraphine",.female, "Hébreu",   "he-IL", "ardente, enflammée", 3, nil, nil, ["spirituel"]),
        fn(472, "Théotime", .male,   "Grec",     "el-GR", "honorant Dieu", 3, nil, nil, ["spirituel"]),
        fn(473, "Ubaldo",   .male,   "Germanique","de-DE","cœur généreux", 3, nil, nil, ["vertu"]),
        fn(474, "Valérie",  .female, "Latin",    "la",    "forte, bien portante", 3, nil, nil, ["force"]),
        fn(475, "Wulfran",  .male,   "Germanique","de-DE","corbeau du loup", 2, nil, nil, ["nature"]),
        fn(476, "Xenia",    .female, "Grec",     "el-GR", "hospitalière", 3, nil, nil, ["vertu"]),
        fn(477, "Yseult",   .female, "Celtique", "cy",    "belle et juste", 2, nil, nil, ["beaute", "classique"]),
        fn(478, "Zachée",   .male,   "Hébreu",   "he-IL", "pur, innocent", 2, nil, nil, ["pureté", "biblique"]),
        fn(479, "Alcyone",  .female, "Grec",     "el-GR", "martin-pêcheur, calme", 3, nil, nil, ["nature", "mythologie"]),
        fn(480, "Benoît",   .male,   "Latin",    "la",    "béni, heureux", 2, nil, nil, ["joie", "spirituel"]),

        fn(481, "Conall",   .male,   "Irlandais","ga-IE", "loup fort", 2, nil, nil, ["force", "nature"]),
        fn(482, "Dymphna",  .female, "Irlandais","ga-IE", "petite cerf", 2, nil, nil, ["nature"]),
        fn(483, "Eithne",   .female, "Irlandais","ga-IE", "noyau, graine", 2, nil, nil, ["nature"]),
        fn(484, "Ferghus",  .male,   "Irlandais","ga-IE", "vigueur virile", 2, nil, nil, ["force"]),
        fn(485, "Grainne",  .female, "Irlandais","ga-IE", "amour, soleil", 2, nil, nil, ["lumiere"]),
        fn(486, "Muireann", .female, "Irlandais","ga-IE", "mer blanche", 3, nil, nil, ["nature", "mer"]),
        fn(487, "Niamh",    .female, "Irlandais","ga-IE", "brillante, radieuse", 2, nil, nil, ["lumiere"]),
        fn(488, "Ruairí",   .male,   "Irlandais","ga-IE", "roi rouge", 3, nil, nil, ["classique"]),
        fn(489, "Sorcha",   .female, "Irlandais","ga-IE", "lumineuse, brillante", 2, nil, nil, ["lumiere"]),
        fn(490, "Turlough", .male,   "Irlandais","ga-IE", "instigateur de guerre", 2, nil, nil, ["force"]),

        fn(491, "Annabelle",.female, "Hébreu",   "he-IL", "grâce et beauté", 3, nil, nil, ["douceur", "beaute"]),
        fn(492, "Bertrand", .male,   "Germanique","de-DE","corbeau brillant", 2, nil, nil, ["classique"]),
        fn(493, "Cécilia",  .female, "Latin",    "la",    "aveugle, céleste", 4, nil, nil, ["classique"]),
        fn(494, "Didier",   .male,   "Latin",    "la",    "désiré, ardent", 3, nil, nil, ["classique"]),
        fn(495, "Ermengarde",.female,"Germanique","de-DE","entière force", 3, nil, nil, ["force"]),
        fn(496, "Fridolin", .male,   "Germanique","de-DE","petit homme libre", 3, nil, nil, ["classique"]),
        fn(497, "Gwenn",    .female, "Breton",   "br",    "blanche", 1, nil, nil, ["pureté"]),
        fn(498, "Hermine",  .female, "Germanique","de-DE","armée entière", 2, nil, nil, ["force"]),
        fn(499, "Ismérie",  .female, "Grec",     "el-GR", "égale de la maison", 3, nil, nil, ["classique"]),
        fn(500, "Josse",    .male,   "Breton",   "br",    "seigneur, maître", 1, nil, nil, ["classique"]),
    ]
    // swiftlint:enable function_body_length

    // MARK: — Private factory

    private static func fn(
        _ id: Int, _ name: String, _ gender: Gender,
        _ origin: String, _ originLocale: String?, _ meaning: String,
        _ syllables: Int,
        _ rankFR: Int?, _ rankUS: Int?,
        _ themes: [String],
        phonetic: String? = nil
    ) -> FirstName {
        FirstName(
            id: id, name: name, gender: gender,
            origin: origin, originLocale: originLocale,
            meaning: meaning, syllables: syllables,
            popularityRankFR: rankFR, popularityRankUS: rankUS,
            themes: themes, phonetic: phonetic
        )
    }
}
