#!/usr/bin/env python3
"""
insert_etymology_top300.py — Insère des étymologies réelles pour les 300 prénoms
les plus populaires en France (sans étymologie en base).

Usage:
    python3 Scripts/insert_etymology_top300.py --dry-run
    python3 Scripts/insert_etymology_top300.py
"""
from __future__ import annotations

import argparse
import shutil
import sqlite3
from pathlib import Path

ROOT      = Path(__file__).parent.parent
DB_PATH   = ROOT / "Resources" / "names.sqlite"
DB_BACKUP = ROOT / "Resources" / "names_before_top300.sqlite"

# ── Etymologies réelles (2-3 phrases, en français) ────────────────────────────

ETYMOLOGIES: dict[str, str] = {
    "Gabriel": "Prénom hébreu issu de גַּבְרִיאֵל (Gavri'el), composé de « gavar » (force, vaillance) et « El » (Dieu), signifiant « homme de Dieu » ou « force divine ». Gabriel est l'archange messager dans la Bible et le Coran, chargé d'annoncer la naissance de Jean-Baptiste et de Jésus. Il est entré dans le calendrier chrétien au Moyen Âge et reste l'un des prénoms les plus répandus en Europe.",
    "Léo": "Prénom latin issu de Leo, qui signifie « lion », symbole de force, de courage et de royauté dans la tradition romaine. Il a été popularisé par plusieurs papes et empereurs, dont Léon Ier le Grand au Ve siècle. Sa forme courte et sonore lui vaut un succès durable dans toute l'Europe francophone.",
    "Raphaël": "Prénom hébreu issu de רָפָאֵל (Rafa'el), composé de « rafa » (guérir) et « El » (Dieu), signifiant « Dieu guérit ». Raphaël est l'un des trois archanges nommés dans les textes bibliques, patron des médecins et des voyageurs. Le prénom a été largement diffusé en Europe grâce au culte catholique et à la célébrité du peintre de la Renaissance Raphaël Sanzio.",
    "Louise": "Prénom féminin d'origine germanique, forme latinisée de Ludovica, dérivé du francique Hlodwig (Clovis, Louis), composé de « hlod » (gloire) et « wig » (combat), signifiant « gloire dans la bataille ». Porté par plusieurs reines et saintes, notamment Louise de Marillac, il est entré dans le calendrier catholique et reste un classique indémodable de la prénomination française.",
    "Jade": "Prénom féminin emprunté au mot « jade », lui-même issu de l'espagnol « piedra de ijada » (pierre des flancs ou des reins), en raison de la croyance ancienne selon laquelle cette pierre guérissait les coliques. Minéral précieux aux teintes vertes caractéristiques, le jade est vénéré depuis des millénaires en Asie et en Mésoamérique comme symbole de pureté et de sagesse. Son usage comme prénom s'est développé en France à partir des années 1990.",
    "Emma": "Prénom germanique dérivé du radical « ermen » ou « irmin », signifiant « universel », « entier » ou « immense », souvent interprété comme « grande force ». Popularisé au Moyen Âge par Emma de Normandie, reine d'Angleterre, il a connu une renaissance mondiale au XXe siècle grâce notamment au roman de Jane Austen et au personnage d'Emma Bovary de Flaubert.",
    "Arthur": "Prénom d'origine celtique, probablement issu du gallois « artos » (ours) ou du latin « Artorius », un gentilice romain dont l'origine reste débattue. Il est indissociable de la légende du roi Arthur et des chevaliers de la Table Ronde, cycle épique du Moyen Âge qui a contribué à sa diffusion dans toute l'Europe. Tombé en désuétude au XVIIe siècle, il est revenu à la mode au XIXe grâce au romantisme.",
    "Lucas": "Prénom latin issu de Lucius ou Lucas, forme latinisée du grec Λουκᾶς (Loukas), probablement dérivé de « lux » (lumière) ou du nom de la région Lucanie en Italie du Sud. Saint Luc, évangéliste et compagnon de saint Paul, lui a donné une forte dimension religieuse dans la tradition chrétienne. Il s'est diffusé dans toute l'Europe sous ses formes locales : Luke, Luca, Lucas.",
    "Maël": "Prénom breton issu du vieux-breton « mael », signifiant « prince » ou « chef », parfois associé à « seigneur » ou « grand ». Porté par plusieurs saints bretons, dont saint Maël, disciple de saint Cadfan au Ve siècle, il est resté vivace en Bretagne avant de connaître un renouveau national en France à partir des années 1990. Il symbolise l'identité celtique et bretonne.",
    "Hugo": "Prénom germanique dérivé du radical « hug » (esprit, intelligence, pensée), que l'on retrouve dans Hugues, Hugh et Ugo. Très répandu au Moyen Âge, il a été porté par plusieurs rois capétiens (Hugues Capet) et saints. Sa popularité contemporaine en France doit beaucoup à Victor Hugo, le grand romancier et poète du XIXe siècle.",
    "Liam": "Prénom irlandais, forme contractée de Uilliam, lui-même adaptation gaélique de Guillaume (William), issu du vieux germanique Willahelm, composé de « wil » (volonté) et « helm » (protection). Très populaire en Irlande depuis des siècles, il s'est répandu dans le monde anglophone avant de s'imposer en France au début du XXIe siècle comme prénom moderne et international.",
    "Alice": "Prénom germanique issu d'Adalheidis (Adelheid en allemand), composé de « adal » (noble) et « heid » (nature, état), signifiant « de noble nature ». La forme française Alice s'est répandue au Moyen Âge ; le prénom a connu un retentissement mondial grâce au roman de Lewis Carroll « Alice au pays des merveilles » (1865). Il évoque à la fois la noblesse médiévale et l'imaginaire de l'enfance.",
    "Camille": "Prénom mixte d'origine latine, issu de Camilla ou Camillus, désignant dans la Rome antique le jeune servant(e) officiant lors des cérémonies religieuses. La Camille de Virgile, guerrière légendaire dans l'Énéide, en a fait un prénom héroïque. Il est entré en France via l'influence latine de l'Église et connaît une popularité régulière depuis le XIXe siècle.",
    "Ethan": "Prénom hébreu issu de אֵיתָן (Eytan), signifiant « solide », « fort », « permanent » ou « robuste ». Mentionné dans l'Ancien Testament comme un sage réputé, il est resté discret en Europe jusqu'à son adoption massive dans les pays anglophones au XXe siècle, avant de se répandre en France dans les années 2000.",
    "Ambre": "Prénom féminin français dérivé du mot « ambre », lui-même issu de l'arabe 'anbar désignant l'ambre gris, substance odorante d'origine marine. La résine fossile appelée ambre jaune (succin) a également contribué à l'imaginaire du prénom, symbole de chaleur et de lumière dorée. Son usage comme prénom féminin s'est développé en France à partir des années 1980-1990.",
    "Paul": "Prénom latin issu de Paulus, signifiant « petit » ou « humble » dans la tradition romaine. Saint Paul, apôtre du christianisme et auteur de nombreuses épîtres du Nouveau Testament, lui a donné une dimension universelle et spirituelle. L'un des prénoms les plus répandus dans l'histoire du monde chrétien, il reste un classique sobre et intemporel.",
    "Lina": "Prénom féminin aux origines multiples : il peut être une forme courte d'Angelina, Carolina ou Paulina (latin), ou dériver de l'arabe لينة (Lina), signifiant « douceur » ou « tendresse ». En Europe, il s'est diffusé comme diminutif de prénoms en -lina avant de s'émanciper comme prénom à part entière au XXe siècle.",
    "Nathan": "Prénom hébreu issu de נָתָן (Nathan), signifiant « il a donné » ou « Dieu a donné ». Dans la Bible, Nathan est le prophète qui reproche à David le meurtre d'Urie et lui annonce les promesses divines. Ce prénom biblique s'est répandu en Europe avec la Réforme protestante et connaît un fort succès en France depuis les années 1990.",
    "Chloé": "Prénom grec issu de Χλόη (Chloê), signifiant « pousse verte », « verdure nouvelle » ou « fleur en bouton », évoquant le renouveau printanier. Dans la mythologie grecque, Chloé est l'un des surnoms de Déméter, déesse de la fertilité. Popularisé par le roman pastoral antique « Daphnis et Chloé » de Longus, il a été adopté en France à partir du XVIIIe siècle.",
    "Eden": "Prénom mixte issu de l'hébreu עֵדֶן (Eden), signifiant « délice », « plaisir » ou « paradis », référence directe au jardin d'Eden de la Genèse. Utilisé d'abord comme prénom masculin dans les pays anglophones, il est devenu mixte et s'est répandu en France au début du XXIe siècle comme prénom évoquant l'idéal et l'innocence.",
    "Gabin": "Prénom français, forme populaire de Gabinus, dérivé latin de Gabii, ancienne ville du Latium. Il a été rendu célèbre en France par l'acteur Jean Gabin (Jean-Alexis Moncorgé), icône du cinéma français du XXe siècle. Sa résurgence en France depuis les années 2000 le place parmi les prénoms rétro-modernes à la fois chaleureux et authentiques.",
    "Rose": "Prénom féminin latin issu de Rosa, désignant la fleur de rose, symbole universel d'amour, de beauté et de pureté. Porté par plusieurs saintes, dont sainte Rose de Lima (première sainte d'Amérique latine), il est répandu dans toute la chrétienté depuis le Moyen Âge. Sa simplicité florale lui assure une popularité constante à travers les siècles.",
    "Léa": "Prénom féminin hébreu issu de לֵאָה (Lea), dont l'étymologie est discutée : « fatiguée » ou « vache sauvage » selon certains, mais plus probablement emprunté à une racine akkadienne signifiant « maîtresse ». Léa est dans la Bible la première épouse de Jacob. Ce prénom biblique s'est largement diffusé en France à partir des années 1990.",
    "Mohamed": "Prénom arabe issu de مُحَمَّد (Muhammad), dérivé du verbe حَمِدَ (hamida), signifiant « louer », « glorifier », d'où « le très loué » ou « digne de louanges ». C'est le prénom du prophète de l'islam, né à La Mecque vers 570 ap. J.-C. L'un des prénoms les plus portés dans le monde, il est présent dans de nombreuses variantes graphiques (Mohammed, Mouhamed, Muhammad).",
    "Tom": "Prénom masculin, forme courte de Thomas, issu du grec Θωμᾶς (Thomas), lui-même translittération de l'araméen תְּאוֹמָא (Toma), signifiant « jumeau ». Saint Thomas, apôtre du Christ, aurait évangélisé l'Inde selon la tradition. Sa forme courte Tom s'est imposée dans les pays anglophones avant de se répandre en Europe.",
    "Lou": "Prénom mixte, diminutif de Louis ou Louise, d'origine germanique (Hlodwig → Clovis), signifiant « gloire dans la bataille ». Utilisé d'abord comme surnom affectueux, Lou est devenu prénom à part entière au XXe siècle. Sa brièveté et sa sonorité douce en font un prénom moderne apprécié aussi bien pour les filles que pour les garçons.",
    "Julia": "Prénom féminin latin issu de Julia, forme féminine de Julius, gentilice de la gens Julia dont Jules César était le plus illustre représentant. Son étymologie renvoie au grec « ioulos » (duvet, première barbe) ou à Iulus, fils d'Énée dans la mythologie romaine. Il s'est répandu dans tout l'empire romain et reste l'un des prénoms latins les plus universels.",
    "Mia": "Prénom féminin aux origines multiples : forme scandinave de Maria (hébreu, « bien-aimée de Dieu »), diminutif d'Amelia en Italie, ou encore prénom autonome en Croatie. Il est aussi associé à l'italienne mia (« ma », terme d'affection). Sa concision et sa musicalité lui ont valu une popularité mondiale croissante depuis la fin du XXe siècle.",
    "Léna": "Prénom féminin, diminutif de Helena (grec Ἑλένη, Helen, « lumière » ou « torche »), ou d'Magdalena (hébreu, « de Magdala »). La forme Léna s'est popularisée en Europe centrale et en Scandinavie avant de s'imposer en France au XXe siècle. Il combine l'héritage classique des prénoms grecs avec une légèreté sonore moderne.",
    "Mila": "Prénom féminin slave issu de « mila », signifiant « chère », « aimée » ou « gracieuse ». Il est courant dans les pays slaves comme diminutif de Milena, Ludmila ou Miloslava. En France, il a gagné en popularité au début du XXIe siècle, porté par son caractère à la fois exotique et facilement prononçable.",
    "Noé": "Prénom masculin hébreu issu de נֹחַ (Noach), signifiant « repos », « consolation » ou « répit ». Noé est le personnage biblique qui, selon la Genèse, construit l'arche pour préserver l'humanité et les animaux du Déluge universel. Ce prénom biblique s'est développé en France surtout à partir des années 2000, porté par son symbolisme de renaissance.",
    "Théo": "Prénom masculin, diminutif de Théodore (grec Θεόδωρος, « don de Dieu ») ou de Théophile (grec, « ami de Dieu »). Il est également une forme courte de Théodore, prénom répandu depuis l'Antiquité grecque. Sa forme raccourcie, légère et dynamique, l'a rendu très populaire en France depuis les années 1990.",
    "Charlie": "Prénom mixte, forme anglaise de Charles, issu du germanique Karl, signifiant « homme libre » ou « homme du peuple ». Charlie s'est popularisé comme diminutif affectueux dans les pays anglophones avant de s'imposer en France comme prénom autonome mixte. L'association au personnage de Charlie Chaplin et à d'autres figures culturelles lui confère une image sympathique et créative.",
    "Juliette": "Prénom féminin français, diminutif de Julie, du latin Julia (gens Julius, « descendante de Jules »). Rendu universel par la tragédie de Shakespeare « Roméo et Juliette » (1597), il est devenu le symbole romantique de l'amour absolu dans la culture occidentale. Sa double syllabe finale douce et sa connotation littéraire en font un grand classique de la prénomination française.",
    "Nolan": "Prénom masculin d'origine irlandaise, issu du gaélique Nuallán, dérivé de « nuall » (cri de guerre, champion) avec le diminutif -án. Il désignait à l'origine un descendant des Nuallán, famille noble irlandaise. Sa modernité sonore et son côté international lui ont assuré un succès croissant en France depuis les années 2000.",
    "Mathis": "Prénom masculin, variante française de Matthias, lui-même issu du grec Ματθίας, adaptation de l'hébreu מַתִּתְיָהוּ (Mattithyahu), signifiant « don de Dieu » ou « cadeau de Yahvé ». Matthias est dans le Nouveau Testament l'apôtre choisi pour remplacer Judas Iscariote. La forme Mathis est spécifiquement française et connaît un succès important depuis les années 1990.",
    "Zoé": "Prénom féminin grec issu de Ζωή (Zoê), signifiant « vie ». Dans le christianisme oriental, Zoé est une traduction grecque du nom hébreu Ève (Havva, « mère des vivants »), ce qui lui confère une dimension spirituelle et symbolique forte. Popularisé par sainte Zoé de Rome, il est en vogue en France depuis les années 1990.",
    "Inès": "Prénom féminin, forme espagnole et portugaise d'Agnès, issu du grec Ἁγνή (Hagnê), signifiant « pure », « chaste ». Sainte Inès (Agnès) de Rome, martyrisée au IIIe siècle, est l'une des saintes les plus vénérées de l'Église. La forme Inès, introduite en France par influence hispanique, s'est imposée comme un prénom à la fois élégant et doux.",
    "Enzo": "Prénom masculin d'origine italienne, probablement diminutif de Lorenzo (Laurent) ou de Vincenzo (Vincent), tous deux d'étymologies latines. Il peut aussi être une forme médiévale italienne de Heinrich (Henri), d'origine germanique (« maître du foyer »). Sa popularité explosive en France depuis les années 1990 le place parmi les grands prénoms mixtes sud-européens.",
    "Lola": "Prénom féminin espagnol, diminutif de Dolores, issu du latin « dolor » (douleur), en référence à Notre-Dame des Douleurs (Virgen de los Dolores). Il s'est émancipé de son étymon douloureux pour devenir un prénom à la personnalité affirmée et à la sonorité festive. En France, il est en vogue depuis les années 1990.",
    "Agathe": "Prénom féminin grec issu de Ἀγαθή (Agathê), forme féminine de Ἀγαθός (Agathos), signifiant « bonne », « vertueuse ». Sainte Agathe de Catane, martyre sicilienne du IIIe siècle, est la patronne des nourrices et des victimes d'éruptions volcaniques. Le prénom est en usage en France depuis le Moyen Âge et connaît un renouveau depuis les années 2000.",
    "Manon": "Prénom féminin français, diminutif affectueux de Marie, lui-même issu de l'hébreu מִרְיָם (Miryam), dont l'étymologie est discutée (« aimée de Dieu », « rebelle » ou « mer amère »). Popularisé par le roman de l'abbé Prévost « Manon Lescaut » (1731) puis par l'opéra de Massenet, il incarne en France un certain idéal de féminité méridionale et romanesque.",
    "Timéo": "Prénom masculin, variante française de Timeo ou Timoteo, issu du grec Τιμόθεος (Timotheos), composé de « timê » (honneur) et « theos » (Dieu), signifiant « qui honore Dieu ». Timothée fut dans le Nouveau Testament le fidèle compagnon de saint Paul. La forme Timéo s'est développée en France au début du XXIe siècle, portée par sa sonorité méditerranéenne.",
    "Victor": "Prénom masculin latin issu de Victor, signifiant « vainqueur » ou « celui qui triomphe ». Répandu dans la Rome antique comme cognomen de soldats victorieux, il a été adopté par le christianisme à travers le culte de nombreux saints martyrs. En France, il est associé à Victor Hugo, géant des lettres du XIXe siècle.",
    "Jeanne": "Prénom féminin, forme française de Johanna, adaptation du grec Ἰωάννα (Ioanna), issu de l'hébreu יוֹחָנָן (Yohanan), signifiant « Dieu est bienveillant » ou « Dieu fait grâce ». Porté par Jeanne d'Arc, héroïne nationale française du XVe siècle, il est indissociable de l'histoire de France et reste un prénom classique et patrimonial.",
    "Inaya": "Prénom féminin arabe issu de عِنَايَة ('inaya), signifiant « soin », « attention », « sollicitude » ou « bienveillance divine ». Il évoque la providence divine et la protection accordée par Dieu. Répandu dans les pays arabophones et au sein des communautés musulmanes en France, il s'est développé comme prénom depuis la fin du XXe siècle.",
    "Romy": "Prénom féminin, diminutif de Rosemarie (combinaison de Rose et Marie) ou de Romaine (féminin de Romain, du latin Romanus, « de Rome »). Il a été mondialement popularisé par l'actrice autrichienne Romy Schneider (1938-1982), dont le style et la personnalité ont marqué le cinéma européen. En France, sa popularité s'est fortement accrue depuis les années 2010.",
    "Marius": "Prénom masculin latin issu de Marius, gentilice romain porté par Caïus Marius, le célèbre général et réformateur de l'armée romaine au Ier siècle av. J.-C. Son étymologie renvoie à « Mars » (dieu de la guerre) ou à « mare » (mer). En France, il est associé aux personnages de Marcel Pagnol (la trilogie marseillaise) et incarne un caractère méridional et chaleureux.",
    "Axel": "Prénom masculin scandinave, variante nordique d'Absalon, lui-même issu de l'hébreu אַבְשָׁלוֹם (Abshalon), signifiant « le père est paix ». La forme Axel s'est développée dans les pays germaniques et nordiques au Moyen Âge avant de se répandre en Europe occidentale au XXe siècle. Sa forte connotation musicale et internationale en fait un prénom moderne très apprécié.",
    "Lucie": "Prénom féminin latin issu de Lucia, dérivé de Lucius, lui-même lié à « lux » (lumière), signifiant « lumineuse », « celle qui est née à l'aube ». Sainte Lucie de Syracuse, martyrisée au IVe siècle, est fêtée le 13 décembre, jour le plus court de l'année dans l'ancien calendrier, renforçant son symbolisme lumineux. Un des prénoms féminins les plus répandus dans l'histoire de l'Europe chrétienne.",
    "Noa": "Prénom mixte hébreu issu de נֹעַ (Noa) pour la forme féminine (signifiant « mouvement » ou « tremblement ») et de נֹחַ (Noach) pour la forme masculine (« repos »). La Noa féminine est dans la Bible l'une des cinq filles de Tselophehad qui ont revendiqué leur héritage. En France, il s'est popularisé comme prénom féminin à partir des années 2010.",
    "Lilou": "Prénom féminin français, diminutif affectueux de Lily ou Liliane, eux-mêmes dérivés du latin « lilium » (lis), fleur symbole de pureté et de royauté. Il peut aussi être une contraction de Lily et Louise. Sa popularité en France a explosé dans les années 2000, associé notamment au film de science-fiction « Le Cinquième Élément » (1997) et à son personnage Leeloo.",
    "Louis": "Prénom masculin, forme française de Ludovicus, latinisation du germanique Hlodwig (Clovis), composé de « hlod » (gloire) et « wig » (combat), signifiant « gloire dans la bataille ». Porté par dix-huit rois de France de Louis Ier à Louis XVIII, il est l'un des prénoms les plus dynastiques de l'histoire française. Toujours populaire, il incarne l'élégance classique à la française.",
    "Lise": "Prénom féminin français, diminutif d'Élisabeth, issu de l'hébreu אֱלִישֶׁבַע (Elisheva), composé de « El » (Dieu) et « sheva » (serment ou plénitude), signifiant « Dieu est mon serment » ou « consacrée à Dieu ». La forme Lise est spécifiquement française et a été portée par de nombreuses figures littéraires et artistiques.",
    "Adèle": "Prénom féminin germanique dérivé du radical « adal » (noble, de haute naissance), que l'on retrouve dans de nombreux prénoms médiévaux (Adélaïde, Adelheid). Sainte Adèle, abbesse mérovingienne, et Adèle de Champagne, reine de France au XIIe siècle, ont contribué à sa diffusion. Le prénom a connu un renouveau international grâce à la chanteuse britannique Adele.",
    "Eléonore": "Prénom féminin d'étymologie incertaine, probablement d'origine provençale ou arabe ; certains le rattachent au grec Ἑλένη (lumière) ou à l'arabe « al-aynur » (la lumière des dieux). Aliénor d'Aquitaine, grande reine du XIIe siècle, en a fait un prénom de prestige royal. Sa forme Éléonore est typiquement française et aristocratique.",
    "Anaïs": "Prénom féminin occitan et catalan, forme méridionale d'Anne, issu de l'hébreu חַנָּה (Hannah), signifiant « grâce », « bienveillance » ou « faveur divine ». Très répandu en Provence et en Catalogne, il s'est popularisé dans l'ensemble de la France au XXe siècle, notamment grâce à l'écrivaine Anaïs Nin. Sa graphie avec tréma lui confère une couleur méditerranéenne distincte.",
    "Clémence": "Prénom féminin latin issu de Clementia, signifiant « clémence », « douceur », « indulgence ». Déesse personnifiant la miséricorde dans la Rome antique, Clémence est devenue une vertu cardinale du christianisme. Le prénom est porté en France depuis le Moyen Âge et incarne la douceur aristocratique.",
    "Elsa": "Prénom féminin germanique, diminutif d'Élisabeth (hébreu, « Dieu est mon serment »). Popularisé dans les pays scandinaves et germaniques, il a été rendu célèbre par le personnage d'Elsa dans l'opéra de Wagner « Lohengrin ». Sa popularité mondiale a explosé en 2013 grâce au film d'animation Disney « La Reine des Neiges ».",
    "Sacha": "Prénom mixte, diminutif russe d'Alexandre, lui-même issu du grec Ἀλέξανδρος (Alexandros), composé de « alexein » (protéger) et « anêr » (homme), signifiant « défenseur des hommes ». Très répandu en Russie et dans les pays slaves, il est entré en France au XXe siècle, apprécié pour sa sonorité internationale et son caractère à la fois doux et fort.",
    "Baptiste": "Prénom masculin latin, issu de Baptiste (latin Baptista, grec Βαπτιστής), signifiant « celui qui baptise ». Il est indissociable de saint Jean-Baptiste, le précurseur du Christ dans les Évangiles. En France, il est souvent utilisé seul mais aussi en composition (Jean-Baptiste), et reste un prénom chrétien classique au caractère sobre et profond.",
    "Léonie": "Prénom féminin latin, forme féminine de Léon (Leo), signifiant « lionne ». Il a été porté par plusieurs saintes et bienheureuses, notamment la sœur de sainte Thérèse de Lisieux. Tombé en désuétude au XXe siècle, Léonie a connu un fort renouveau en France depuis les années 2010 dans la vogue des prénoms anciens rétro.",
    "Maxime": "Prénom masculin latin issu de Maximus, signifiant « le plus grand », « le plus grand ». Surnom romain d'honneur attribué aux généraux victorieux, il a été porté par de nombreux saints et empereurs. En France, il est populaire depuis les années 1990 et incarne la confiance et l'ambition.",
    "Mathilde": "Prénom féminin germanique issu de Mahthildis, composé de « maht » (force, puissance) et « hild » (combat, bataille), signifiant « puissante dans la bataille ». Mathilde de Flandre, épouse de Guillaume le Conquérant, en a fait un prénom royal. Il connaît depuis les années 1990 un retour en grâce comme prénom classique et élégant.",
    "Océane": "Prénom féminin français dérivé du latin Oceanus, lui-même du grec Ὠκεανός (Okeanos), désignant le dieu des eaux primordiales dans la mythologie grecque, puis par extension l'océan. Son usage comme prénom s'est développé en France à partir des années 1980, porté par sa dimension poétique et naturelle.",
    "Elisa": "Prénom féminin, diminutif d'Élisabeth, issu de l'hébreu אֱלִישֶׁבַע (Elisheva), « Dieu est mon serment » ou « consacrée à Dieu ». Largement répandu en Italie, Espagne et France, il est perçu comme une forme plus légère et méditerranéenne du prénom complet. Sa popularité en France est constante depuis la fin du XXe siècle.",
    "Clara": "Prénom féminin latin issu de Clara, forme féminine de Clarus, signifiant « claire », « lumineuse », « illustre ». Sainte Claire d'Assise, fondatrice des clarisses au XIIIe siècle et compagne de saint François, en a fait un prénom de renommée mondiale. Il est porteur d'une image de pureté, d'intelligence et de rayonnement.",
    "Margot": "Prénom féminin français, diminutif de Marguerite, issu du grec Μαργαρίτης (Margaritês), signifiant « perle ». Popularisé par Margot de Navarre (Marguerite de Valois, « la Reine Margot »), il a eu une longue éclipse avant de connaître une résurgence forte dans les années 2000. Son caractère espiègle et naturel lui assure une popularité constante.",
    "Hugo": "Prénom germanique dérivé du radical « hug » (esprit, intelligence, pensée), que l'on retrouve dans Hugues, Hugh et Ugo. Très répandu au Moyen Âge, il a été porté par plusieurs rois capétiens (Hugues Capet) et saints. Sa popularité contemporaine en France doit beaucoup à Victor Hugo, le grand romancier et poète du XIXe siècle.",
    "Augustin": "Prénom masculin latin issu d'Augustinus, dérivé d'Augustus (« vénérable », « sacré »), lui-même de « augere » (augmenter, consacrer). Saint Augustin d'Hippone, père de l'Église et auteur des « Confessions » (IVe-Ve siècle), en a fait un prénom de haute culture spirituelle. En France, il appartient aux prénoms patriciens en vogue depuis les années 2000.",
    "Antoine": "Prénom masculin latin issu d'Antonius, gentilice romain d'origine étrusque dont l'étymologie exacte est incertaine, parfois rattaché au grec « anthos » (fleur). Rendu illustre par Marc Antoine, général romain, et saint Antoine de Padoue, l'un des saints les plus populaires du catholicisme. Un des prénoms les plus répandus de l'histoire française.",
    "Célia": "Prénom féminin latin, dérivé de Caelia, forme féminine du gentilice Caelius, rattaché à « caelum » (ciel), signifiant « du ciel » ou « céleste ». Il peut aussi être un diminutif de Céline ou de Marcélia. Ce prénom ensoleillé s'est répandu en France et en Espagne au XXe siècle.",
    "Iris": "Prénom féminin grec issu d'Ἶρις (Iris), déesse de l'arc-en-ciel dans la mythologie grecque, messagère des dieux entre le ciel et la terre. Le mot grec désigne aussi la fleur iris (lys), symbole de royauté française (fleur de lys). Utilisé en France depuis le XIXe siècle, il connaît un renouveau au XXIe siècle pour son côté nature et poétique.",
    "Léon": "Prénom masculin latin issu de Leo, signifiant « lion », emblème de force et de royauté. Porté par treize papes (dont Léon Ier le Grand) et de nombreux souverains, il a traversé les siècles avec autorité. Sa résurgence en France depuis les années 2010 le place parmi les prénoms rétro-modernes préférés des parents.",
    "Maëlys": "Prénom féminin breton composé de « mael » (prince, chef) et du suffixe -ys, diminutif affectueux breton. Apparu en France à la fin du XXe siècle, il est une création moderne influencée par la tradition bretonne. Sa douceur sonore et sa coloration celtique lui assurent une popularité croissante depuis les années 2000.",
    "Luca": "Prénom masculin, forme italienne de Luc, issu du grec Λουκᾶς (Loukas), latinisé en Lucas, probablement de « lux » (lumière) ou du nom de la Lucanie. Saint Luc, évangéliste et médecin selon la tradition, lui a donné sa dimension spirituelle. En France, la forme italienne Luca s'est répandue au début du XXIe siècle.",
    "Clément": "Prénom masculin latin issu de Clemens, signifiant « doux », « clément », « indulgent ». Porté par plusieurs papes, dont saint Clément Ier (Ier siècle), successeur de saint Pierre, il a une longue tradition chrétienne. En France, il reste un prénom classique et apprécié, évoquant la douceur et la sagesse.",
    "Capucine": "Prénom féminin français dérivé de « capucine », fleur du genre Tropaeolum originaire d'Amérique du Sud, nommée ainsi car sa forme évoque le capuchon (« capuce ») des moines capucins. Son usage comme prénom s'est développé en France au XXe siècle, associé à la célèbre actrice française Capucine (Germaine Lefebvre). Il incarne la fantaisie et la joie de vivre.",
    "Eliot": "Prénom masculin, forme anglaise d'Elie, issu de l'hébreu אֵלִיָּהוּ (Eliyahu), signifiant « mon Dieu est Yahvé ». Cette forme anglicisée, popularisée par le romancier George Eliot (pseudonyme de Mary Ann Evans) et l'auteur T.S. Eliot, s'est répandue en France au début du XXIe siècle comme prénom moderne et international.",
    "Samuel": "Prénom masculin hébreu issu de שְׁמוּאֵל (Shemu'el), généralement interprété comme « Dieu l'a entendu » ou « son nom est Dieu », de « shem » (nom) et « El » (Dieu). Samuel est dans la Bible le dernier juge d'Israël, qui sacra Saül et David. Ce prénom biblique s'est répandu dans toute la chrétienté et connaît une popularité régulière en France.",
    "Emilie": "Prénom féminin latin issu d'Aemilia, forme féminine du gentilice Aemilius, dont l'étymologie renvoie au latin « aemulus » (rival, émule) ou à une origine étrusque. La gens Aemilia était l'une des grandes familles de la République romaine. En France, le prénom Émilie a connu son apogée dans les années 1980-1990.",
    "Timothée": "Prénom masculin grec issu de Τιμόθεος (Timotheos), composé de « timê » (honneur, estime) et « theos » (Dieu), signifiant « qui honore Dieu ». Timothée fut le fidèle compagnon de voyage de saint Paul, à qui l'apôtre adressa deux épîtres. Peu répandu en France jusqu'aux années 2000, il connaît un renouveau parmi les prénoms chrétiens classiques.",
    "Robin": "Prénom masculin, diminutif médiéval de Robert, issu du germanique Hrodebert, composé de « hrod » (gloire) et « beraht » (brillant), signifiant « gloire brillante ». La figure légendaire de Robin des Bois (Robin Hood), héros populaire anglais du Moyen Âge, en a fait un prénom associé à la bravoure et à la justice. En France, il est apprécié depuis les années 1990.",
    "Quentin": "Prénom masculin latin issu de Quintinus, dérivé de Quintus (« le cinquième »), prénom romain attribué au cinquième enfant d'une fratrie. Saint Quentin, martyr du IIIe siècle dont le culte est centré à Saint-Quentin en Picardie, lui a donné sa dimension religieuse en France. C'est un prénom typiquement français, populaire depuis les années 1980.",
    "Laura": "Prénom féminin latin issu de Laura, dérivé de « laurus » (laurier), arbre symbole de gloire et de victoire dans la Rome antique. Immortalisé par Pétrarque, poète florentin du XIVe siècle, qui voua une passion littéraire à une Laure de Noves, le prénom a traversé les siècles auréolé de romantisme. Très répandu dans les pays latins depuis la Renaissance.",
    "Sarah": "Prénom féminin hébreu issu de שָׂרָה (Sarah), signifiant « princesse », « noble dame » ou « souveraine ». Sara, épouse d'Abraham dans la Bible, est la mère du peuple hébreu et figure fondatrice des trois religions abrahamiques. Ce prénom biblique est universellement répandu et reste un des prénoms féminins les plus portés dans le monde.",
    "Raphaëlle": "Prénom féminin, forme française féminisée de Raphaël, issu de l'hébreu רָפָאֵל (Rafa'el), signifiant « Dieu guérit ». L'archange Raphaël est dans la tradition biblique le guérisseur céleste. La forme féminine Raphaëlle s'est développée en France au XXe siècle et connaît un regain de popularité depuis les années 2000.",
    "Simon": "Prénom masculin hébreu issu de שִׁמְעוֹן (Shimon), dérivé de « shama » (écouter, entendre), signifiant « Dieu a entendu ». Simon Pierre est dans les Évangiles le premier apôtre de Jésus, qui lui donne le nom Pierre (grec Petros, « roc »). Un des prénoms bibliques les plus répandus dans le monde chrétien.",
    "Céleste": "Prénom mixte latin issu de Caelestis, signifiant « céleste », « du ciel ». Porté par cinq papes (dont Célestin Ier), il a une longue tradition chrétienne. En France, sa dimension poétique et sa rareté relative lui valent un renouveau comme prénom original et lumineux depuis les années 2010.",
    "Alexis": "Prénom masculin grec issu d'Ἀλέξιος (Alexios), dérivé de « alexein » (défendre, protéger), signifiant « défenseur » ou « protecteur ». Répandu dans l'Empire byzantin chez les empereurs de la famille Comnène, il s'est diffusé en Europe occidentale via l'influence orthodoxe et le culte de saint Alexis d'Édesse. En France, il est populaire depuis les années 1980.",
    "Eva": "Prénom féminin, forme latinisée d'Ève, issu de l'hébreu חַוָּה (Havva), lui-même dérivé de « havah » (vivre, être vivant), signifiant « mère des vivants » ou « source de vie ». Ève est dans la Genèse la première femme créée par Dieu. La forme Eva est répandue dans toute l'Europe latine et germanique.",
    "Bastien": "Prénom masculin, diminutif français de Sébastien, issu du latin Sebastianus, lui-même du grec Σεβαστός (Sebastos), titre d'honneur romain équivalent à « Auguste » ou « vénérable ». Saint Sébastien, martyr du IIIe siècle, est l'un des saints les plus représentés dans l'art chrétien. La forme courte Bastien s'est imposée comme prénom autonome en France.",
    "Estelle": "Prénom féminin, d'origine provençale ou latine, dérivé de « stella » (étoile). Il peut aussi venir du provençal « Estela ». Rendu célèbre par Estelle, personnage du roman de Charles Dickens, et porté par plusieurs saintes, il évoque la luminosité et le scintillement. Sa popularité en France est constante depuis le XIXe siècle.",
    "Damien": "Prénom masculin grec issu de Δαμιανός (Damianos), dont l'étymologie renvoie à Δαμία (Damia), surnom de Cybèle, déesse de la terre, ou à « daman » (dompter). Saints Côme et Damien, médecins martyrs du IIIe siècle, sont les patrons des chirurgiens. Ce prénom est répandu en France depuis le Moyen Âge.",
    "Jade": "Prénom féminin emprunté au mot « jade », lui-même issu de l'espagnol « piedra de ijada » (pierre des flancs ou des reins), en raison de la croyance ancienne selon laquelle cette pierre guérissait les coliques. Minéral précieux aux teintes vertes caractéristiques, le jade est vénéré depuis des millénaires en Asie et en Mésoamérique comme symbole de pureté et de sagesse. Son usage comme prénom s'est développé en France à partir des années 1990.",
    "Matteo": "Prénom masculin, forme italienne de Matthieu, issu de l'hébreu מַתִּתְיָהוּ (Mattithyahu), signifiant « don de Dieu » ou « cadeau de Yahvé ». Saint Matthieu, l'un des douze apôtres et évangéliste, lui a donné sa forte empreinte chrétienne. La forme italienne Matteo s'est popularisée en France au début du XXIe siècle dans la vogue des prénoms italo-méditerranéens.",
    "Justine": "Prénom féminin latin issu de Justina, forme féminine de Justinus, dérivé de Justus (« juste »), lui-même de « jus » (droit, loi). Plusieurs saintes Justine sont vénérées dans l'Église catholique, dont Justine de Padoue, martyre du IVe siècle. En France, Justine est en vogue depuis les années 1980 et évoque la droiture et l'équité.",
    "Soren": "Prénom masculin scandinave, forme danoise de Severinus, issu du latin « severus » (sévère, austère, sérieux). Popularisé par le philosophe danois Søren Kierkegaard (XIXe siècle), fondateur de l'existentialisme, le prénom Soren est entré en France comme un prénom nordique intellectuel et distinctif.",
    "Yasmine": "Prénom féminin arabe et persan issu de يَاسَمِين (Yasmin), nom de la fleur de jasmin, qui tire lui-même son nom du persan yâsamîn. Le jasmin, symbole de douceur et de pureté dans les cultures arabe et perse, en fait un prénom à la fois floral et poétique. Répandu dans les pays arabophones et en France depuis la fin du XXe siècle.",
    "Mathieu": "Prénom masculin, forme française de Matthieu, issu de l'hébreu מַתִּתְיָהוּ (Mattithyahu), signifiant « don de Dieu ». Saint Matthieu, apôtre et évangéliste, collecteur d'impôts converti par Jésus, en a fait un prénom chrétien fondamental. La forme Mathieu (sans « h ») est typiquement française et a connu son apogée dans les années 1980.",
    "Ophélie": "Prénom féminin grec issu d'Ὀφελία (Ophelia), dérivé de « ophelos » (aide, secours, avantage). Popularisé dans toute l'Europe par le personnage d'Ophélie dans « Hamlet » de Shakespeare (vers 1600), jeune femme à la beauté tragique, il est devenu un prénom romantique par excellence. En France, il s'est répandu au XIXe siècle avec le romantisme.",
    "Solène": "Prénom féminin breton dérivé de Saulina ou Solinne, lui-même lié au latin « solemnis » (solennel, sacré) ou à « sol » (soleil). Sainte Solène (Soline) de Chartres, martyre des premiers siècles chrétiens, en a fait un prénom régional breton. Sa modernité sonore et sa consonance bretonne lui valent un succès durable en France.",
    "Théodore": "Prénom masculin grec issu de Θεόδωρος (Theodoros), composé de « theos » (Dieu) et « doron » (don), signifiant « don de Dieu ». Plusieurs saints et empereurs byzantins ont porté ce prénom, qui a traversé l'Europe médiévale via l'Église orthodoxe et catholique. Sa résurgence en France depuis les années 2000 le place parmi les prénoms patriciens revigorés.",
    "Constance": "Prénom féminin latin issu de Constantia, dérivé de Constans (« constant », « persévérant », « ferme »). Porté par plusieurs impératrices romaines et reines médiévales, il a une longue tradition aristocratique. En France, sa résurgence depuis les années 2000 en fait un prénom élégant et intemporel.",
    "Adrien": "Prénom masculin latin issu d'Hadrianus, désignant à l'origine un habitant de la ville d'Hadria (aujourd'hui Adria, en Vénétie). L'empereur Hadrien, qui fit construire le célèbre mur en Bretagne romaine, en est la figure historique la plus connue. Plusieurs papes ont porté ce prénom, dont Hadrien Ier qui collabora avec Charlemagne.",
    "Giulia": "Prénom féminin, forme italienne de Julie, du latin Julia (gens Julius, famille de Jules César). Son étymologie renvoie à Iulus, fils légendaire d'Énée, ancêtre mythique des Romains. En France, la forme italienne Giulia s'est popularisée au début du XXIe siècle, portée par son élégance italienne et sa sonorité distincte.",
    "Félix": "Prénom masculin latin issu de Felix, signifiant « heureux », « chanceux », « fertile ». Surnom de bon augure dans la Rome antique, il a été adopté par de nombreux saints chrétiens (dont quatre papes) et empereurs. En France, il est apprécié pour sa légèreté et son optimisme inhérent.",
    "Florian": "Prénom masculin latin issu de Florianus, dérivé de Florus (« fleuri », « florissant »), lui-même de « flos » (fleur). Saint Florian, officier romain martyr du IIIe siècle, est le patron des pompiers et de la Pologne. En France, le prénom est en vogue depuis les années 1980.",
    "Amélie": "Prénom féminin germanique issu d'Amalia, dérivé du radical « amal » (travail, labeur), nom d'une grande famille ostrogothe médiévale. Popularisé en France grâce au film « Le Fabuleux Destin d'Amélie Poulain » (2001), il est devenu un prénom emblématique de la féminité française contemporaine.",
    "Théa": "Prénom féminin grec issu de Θεά (Thea), signifiant « déesse » ou « divine ». Dans la mythologie grecque, Théia est la déesse de la lumière et mère d'Hélios (Soleil), Séléné (Lune) et Éos (Aurore). En France, ce prénom court et lumineux s'est popularisé au début du XXIe siècle.",
    "Alexia": "Prénom féminin grec, forme féminine d'Alexis, dérivé de « alexein » (protéger, défendre), signifiant « protectrice ». Répandu dans les pays méditerranéens, il a connu un pic de popularité en France dans les années 1990-2000. Sa sonorité grecque et sa douceur en font un prénom à la fois classique et moderne.",
    "Elio": "Prénom masculin d'origine grecque ou italienne, dérivé d'Hélios (grec Ἥλιος), le dieu du Soleil dans la mythologie grecque. En Italie, il est aussi considéré comme un diminutif d'Aurelio ou d'Emilio. Sa popularité en France au XXIe siècle est associée à son caractère solaire et méditerranéen.",
    "Louna": "Prénom féminin, variante graphique de Luna, issu du latin « luna » (lune). Le prénom Luna évoque la déesse Diane, personnification romaine de la Lune, symbole de féminité et de mystère. La graphie Louna, plus douce et française, s'est développée en France au début du XXIe siècle.",
    "Youssef": "Prénom masculin arabe issu de يُوسُف (Yusuf), translittération arabe de l'hébreu יוֹסֵף (Yosef), signifiant « Dieu ajoutera » ou « Dieu multipliera ». Joseph est dans la Bible le fils préféré de Jacob, vendu en esclavage en Égypte où il devient conseiller du pharaon. Youssef est la forme arabe la plus répandue de ce prénom universel.",
    "Maxence": "Prénom mixte latin issu de Maxentius, dérivé de Maximus (« le plus grand »). Maxence (Marcus Aurelius Valerius Maxentius) fut un empereur romain du IVe siècle, rival de Constantin Ier. En France, le prénom s'est répandu au XXe siècle, apprécié pour sa sonorité aristocratique et son ambiguïté de genre.",
    "Thibault": "Prénom masculin germanique issu de Theobald, composé de « theud » (peuple) et « bald » (audacieux, courageux), signifiant « courageux parmi le peuple ». Très répandu au Moyen Âge, notamment porté par des comtes de Champagne et des rois de Navarre, il a connu une résurgence en France à partir des années 1980 dans la vague des prénoms médiévaux.",
    "Corentin": "Prénom masculin breton, issu du vieux-breton « Kaourantinn » ou « Corentinus », dont l'étymologie est incertaine, peut-être liée à « cor » (cour royale) ou à une racine celtique signifiant « ami des tempêtes ». Saint Corentin, premier évêque de Quimper au Ve siècle, est l'un des saints fondateurs de la Bretagne. Resté vivace en Bretagne, il s'est diffusé dans toute la France à partir des années 1990.",
    "Inès": "Prénom féminin, forme espagnole et portugaise d'Agnès, issu du grec Ἁγνή (Hagnê), signifiant « pure », « chaste ». Sainte Inès (Agnès) de Rome, martyrisée au IIIe siècle, est l'une des saintes les plus vénérées de l'Église. La forme Inès, introduite en France par influence hispanique, s'est imposée comme un prénom à la fois élégant et doux.",
    "Lorenzo": "Prénom masculin, forme italienne de Laurent, issu du latin Laurentius, désignant à l'origine un habitant de Laurentum, ville du Latium liée au laurier (« laurus »). Saint Laurent, diacre martyr du IIIe siècle, est l'un des saints les plus populaires du catholicisme. La forme italienne Lorenzo s'est popularisée en France au début du XXIe siècle.",
    "Valentin": "Prénom masculin latin issu de Valentinus, dérivé de Valens (« fort », « vigoureux », « en bonne santé »). Saint Valentin, évêque martyr du IIIe siècle, est devenu le patron des amoureux selon une tradition médiévale anglaise. La fête de la Saint-Valentin le 14 février lui a assuré une notoriété universelle au-delà du monde chrétien.",
    "Maeva": "Prénom féminin d'origine polynésienne, issu du tahitien « Maeva », signifiant « bienvenue » ou « sois la bienvenue ». Il est aussi utilisé comme interjection d'accueil festif dans les cultures polynésiennes. Son adoption en France métropolitaine à partir des années 1980 s'est faite via les liens culturels avec la Polynésie française.",
    "Yael": "Prénom féminin hébreu issu de יָעֵל (Ya'el), signifiant « bouquetin » ou « chèvre de montagne », symbole d'agilité et de liberté dans la culture hébraïque. Yaël est dans la Bible l'héroïne qui tua le général cananéen Sisera en plantant un piquet dans sa tempe. Ce prénom courageux et naturel s'est répandu en Israël et dans les communautés juives du monde entier.",
    "Blanche": "Prénom féminin français, du latin « blanca » ou du germanique « blank » (blanc, brillant, pur). Porté par des reines médiévales prestigieuses comme Blanche de Castille, mère de saint Louis IX et régente de France, il est indissociable de l'histoire royale française. Sa résurgence en France depuis les années 2010 en fait un prénom patrimonial très apprécié.",
    "Eugène": "Prénom masculin grec issu d'Εὐγένιος (Eugenios), composé de « eu » (bien) et « genos » (naissance, race), signifiant « bien né » ou « de noble naissance ». Porté par plusieurs papes et empereurs, dont Eugène de Beauharnais, beau-fils de Napoléon, il est fortement associé au XIXe siècle. Sa résurgence en France au XXIe siècle est portée par la vogue des prénoms anciens.",
    "Mael": "Prénom masculin breton issu du vieux-breton « mael », signifiant « prince » ou « chef ». Porté par plusieurs saints bretons, dont saint Maël, disciple de saint Cadfan au Ve siècle, il est resté vivace en Bretagne avant de connaître un renouveau national en France à partir des années 1990. Cette variante sans tréma est la graphie alternative la plus répandue.",
    "Nadia": "Prénom féminin slave, diminutif de Nadejda ou Nadezhda, du slave « nadezhda » (espérance). Popularisé en Europe occidentale via la diaspora slave au XXe siècle, il est notamment connu grâce à la gymnaste roumaine Nadia Comaneci, première à obtenir un 10 parfait aux Jeux olympiques de 1976. Sa sonorité douce et internationale lui assure un succès constant en France.",
    "Ewen": "Prénom masculin breton et gallois, forme bretonne d'Yves ou Yvon, issu du vieux-celtique « ivo » (if, l'arbre), ou de l'irlandais « eoghan » (né du if). L'if est un arbre sacré dans les cultures celtiques, symbole d'éternité et de renaissance. Très répandu en Bretagne, Ewen s'est diffusé dans toute la France comme prénom celtique authentique.",
    "Colette": "Prénom féminin français, diminutif de Nicole, lui-même du grec Νικόλαος (Nikolaos), composé de « nikê » (victoire) et « laos » (peuple), signifiant « victoire du peuple ». Sainte Colette (Nicolette) de Corbie, réformatrice des clarisses au XVe siècle, lui a donné une dimension religieuse. L'écrivaine Colette (Sidonie-Gabrielle Colette) en a fait un prénom littéraire.",
    "Marguerite": "Prénom féminin, du grec Μαργαρίτης (Margaritês), signifiant « perle ». Porté par de nombreuses saintes et reines (Marguerite de Valois, Marguerite de Navarre), il est un grand classique de l'histoire française. Sa résurgence contemporaine le place parmi les prénoms rétro les plus choisis pour leur noblesse et leur caractère fleuri.",
    "Oscar": "Prénom masculin d'origine irlandaise ou nordique, probablement du gaélique « os » (cerf) et « cara » (ami), signifiant « ami des cerfs », ou du vieux-norrois « áss » (dieu) et « geir » (lance). Popularisé en Europe par les poèmes d'Ossian (James Macpherson, 1760), il a été adopté par Napoléon qui le donna à son filleul Oscar Ier de Suède. Il évoque aussi le prix cinématographique américain.",
    "Philomène": "Prénom féminin grec issu de Φιλoμήνη (Philomenê), composé de « philos » (ami, qui aime) et « menos » (force, désir), signifiant « celle qui aime la force » ou « amie des forces ». Sainte Philomène, dont le culte connut une popularité immense au XIXe siècle avant d'être réexaminé par l'Église, a diffusé ce prénom. Il est en vogue à nouveau dans les années 2010.",
    "Priscille": "Prénom féminin latin, diminutif de Prisca (« ancienne », « vénérable »), dérivé de « priscus » (ancien, primitif). Priscille et Aquilas sont dans le Nouveau Testament un couple chrétien qui hébergea saint Paul et contribua à l'évangélisation. Peu répandu mais distinctif, ce prénom évoque l'Antiquité chrétienne et la tradition.",
    "Anatole": "Prénom masculin grec issu d'Ἀνατολή (Anatolê), signifiant « levant », « orient » ou « soleil levant ». Dans la géographie ancienne, l'Anatolie désignait l'Asie Mineure (la Turquie actuelle). Ce prénom rare en France incarne une ouverture vers l'orient et la lumière ; il est associé à l'écrivain Anatole France, prix Nobel de littérature 1921.",
    "Eulalie": "Prénom féminin grec issu d'Εὐλαλία (Eulalia), composé de « eu » (bien) et « lalein » (parler), signifiant « qui parle bien », « éloquente ». Sainte Eulalie de Barcelone et sainte Eulalie de Mérida, toutes deux martyres du IVe siècle, ont donné à ce prénom une forte empreinte hispano-chrétienne. En France, il est porteur d'une ancienneté et d'une douceur musicale.",
    "Malo": "Prénom masculin breton, issu du vieux-breton « Maclou » ou « Maclovius », latinisation d'un nom celtique composé de « mach » (garantie, otage) et « lou » (lumière, gloire). Saint Malo (Maclovius), évêque breton du VIe siècle, est le patron de la ville de Saint-Malo. Ce prénom solidement ancré dans la tradition bretonne s'est diffusé dans toute la France depuis les années 2000.",
    "Titouan": "Prénom masculin breton, forme bretonne de Sébastien ou de Titien (Tiziano). Issu du breton « Ti-touan » ou latinisé de formes celtiques, il peut aussi renvoyer au peintre Titien de la Renaissance. Très répandu en Bretagne depuis les années 1990, il est désormais populaire dans toute la France pour son caractère celtique et moderne.",
    "Ilona": "Prénom féminin hongrois, forme magyare d'Hélène, issu du grec Ἑλένη (Helênê), signifiant « lumineuse », « torche » ou « lumière du soleil ». En Hongrie, Ilona est un prénom très courant depuis le Moyen Âge. En France, il s'est répandu au XXe siècle, apprécié pour sa sonorité douce et son exotisme d'Europe centrale.",
    "Solange": "Prénom féminin français d'origine latine, probablement dérivé de « solemnis » (solennel, sacré) ou du latin « solum » (seul, unique) et « angelus » (ange). Sainte Solange, bergère du Berry martyrisée au IXe siècle, est la patronne de la province du Berry. Ce prénom ancré dans la tradition catholique française reste un prénom régional attachant.",
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="Affiche ce qui serait écrit, sans modifier la base")
    args = parser.parse_args()

    if not DB_PATH.exists():
        raise SystemExit(f"❌  DB introuvable : {DB_PATH}")

    # Vérifie lesquels existent dans la base et n'ont pas encore d'étymologie
    con = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    existing = {
        row[0]
        for row in con.execute(
            "SELECT name FROM names WHERE etymology IS NULL OR etymology = ''"
        ).fetchall()
    }
    con.close()

    to_write = {name: etym for name, etym in ETYMOLOGIES.items() if name in existing}
    already_done = [name for name in ETYMOLOGIES if name not in existing]

    print(f"\n  Étymologies disponibles dans ce script : {len(ETYMOLOGIES)}")
    print(f"  Déjà renseignées en base (ignorées)    : {len(already_done)}")
    print(f"  À écrire                               : {len(to_write)}")

    if already_done:
        print(f"\n  Déjà présentes : {', '.join(already_done[:10])}{'…' if len(already_done) > 10 else ''}")

    if not to_write:
        print("\n  Rien à écrire.")
        return

    if args.dry_run:
        print("\n[DRY-RUN] Exemples :")
        for name, etym in list(to_write.items())[:3]:
            print(f"  {name}: {etym[:100]}…")
        print("\n[DRY-RUN] Aucune écriture effectuée.")
        return

    print(f"\n⚠️  Prêt à écrire {len(to_write)} étymologies dans {DB_PATH.name}")
    confirm = input("  Confirmer ? [o/N] ").strip().lower()
    if confirm != "o":
        print("  Annulé.")
        return

    shutil.copy2(DB_PATH, DB_BACKUP)
    print(f"✓ Backup : {DB_BACKUP.name}")

    con = sqlite3.connect(DB_PATH)
    written = 0
    for name, etym in to_write.items():
        rows = con.execute(
            "UPDATE names SET etymology = ? WHERE name = ? AND (etymology IS NULL OR etymology = '')",
            (etym, name),
        ).rowcount
        written += rows

    con.commit()
    con.close()

    print(f"✓ {written} prénoms mis à jour.")

    # Rapport
    con = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    total = con.execute("SELECT COUNT(*) FROM names").fetchone()[0]
    with_etym = con.execute(
        "SELECT COUNT(*) FROM names WHERE etymology IS NOT NULL AND etymology != ''"
    ).fetchone()[0]
    con.close()
    print(f"\n── Couverture étymologie ─────────────────────")
    print(f"  Avec étymologie : {with_etym:>7,}  ({100*with_etym//total}%)")
    print(f"  Sans étymologie : {total - with_etym:>7,}  ({100*(total - with_etym)//total}%)")
    print(f"  Total           : {total:>7,}")
    print(f"\n→ Pour les {total - with_etym:,} restants, lance :")
    print(f"  ANTHROPIC_API_KEY=sk-ant-... python3 Scripts/enrich_etymology.py --priority-only")


if __name__ == "__main__":
    main()
